### PR TITLE
Fix selection start point lagging behind cursor

### LINKED ISSUE #1366: Selection misses first character
Selecting in alacritty often misses the first character. Other terminals (such as urxvt and xterm) always include the first character in the selection even if only part of it is selected.

Edit: I should add that this was tested on scrollback@4631ca4

Alacritty:
alacritty_selection

Urxvt
urxvt_selection

### PR DESCRIPTION
**Pull request by chrisduerr**
Since the mouse start position has been the first movement event after
the mouse button was held down, there have been some issues with the
start point lagging behind the cursor because movement events were not
reported from the initial position but there was a gap until movement
starts reporting.

To fix this whenever the mouse button is pressed, the position and cell
side is stored on the `Mouse` struct. Because of this it does not matter
anymore if the movement events are all reported and we can just start a
selection using the stored position/side whenever there currently is no
selection present.

This fixes #1366.

### CODE REVIEW

File: src/event.rs [hunk 1]
```diff
@@ -173,6 +184,11 @@ impl Default for Mouse {
             column: Column(0),
             cell_side: Side::Left,
             lines_scrolled: 0.0,
+            selection_start_pos: Point {
+                line: Line(0),
+                col: Column(0),
+            },
+            selection_start_side: Side::Left,
```
Comment (nixpulvis) [inline src/event.rs]: Would it be better to have these be `Option` types? Could that remove the need for a `selection_started` function? I just feel a little weird about these defaults.

File: src/input.rs [hunk 2]
```diff
@@ -269,44 +271,41 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
...
-                }, cell_side);
+                if self.ctx.selection_started() {
+                    self.ctx.update_selection(Point {
+                        line: point.line,
+                        col: point.col
+                    }, cell_side);
+                } else {
+                    let pos = self.ctx.mouse().selection_start_pos;
+                    let side = self.ctx.mouse().selection_start_side;
+                    self.ctx.update_selection(pos, side);
```
Comment (nixpulvis) [inline src/input.rs]: Really small nitpick, but we're using the words `point` and `pos` interchangeably. Might be nice to clean that up. That's a larger refactor, I understand if you don't want to make it.

File: src/event.rs (hunk 1 above)
Comment (chrisduerr) [reply src/event.rs]: The defaults are irrelevant but I've chosen to go with "random" defaults over `Option` because it makes accessing them a lot easier.

The `selection_started` method would still be needed unless we clear the `selection_start_side/pos` whenever the selection itself is cleared. I've thought about doing it this way but then decided to go with the current implementation before I've added the `selection_started` method.

I think it might be a viable solution to replace selection start/end with an option and then remove the `selection_started` method, I'll investigate this further just to check if this cleans up the code. Sounds like a good idea, thanks!

File: src/input.rs (hunk 2 above)
Comment (chrisduerr) [reply src/input.rs]: Yeah while writing this code I wasn't entirely sure if I should just rename `selection_start_pos` to `selection_start_point`. In theory it's both the same thing because a `Point` is just a position somewhere in the grid.

I think I just went for `pos` because it's shorter tbh, if you already got confused by this it might make sense to change it just for consistency.

File: src/event.rs (hunk 1 above)
Comment (chrisduerr) [reply src/event.rs]: So after I remembered why I did things the way I did, I wrote about 7 paragraphs explaining why I wasn't able to come up with a simpler solution for this. And after those 7 paragraphs I came up with a simpler solution for this.

So hopefully the changes in my latest commit make things a little better. Let me know if you have any feedback about these changes @nixpulvis!

**Comment by nixpulvis** [comment]
LGTM, working on all my machines. Most notably my laptop where I was seeing this issue before. :tada: :heart:

**Comment by chrisduerr** [comment]
Until now I've just kinda assumed that starting the selection in the `on_mouse_pressed` method wouldn't work because otherwise that would have already been the case.

I kinda expected empty selections to overwrite the last selection copied to clipboard in X11 but that doesn't seem to be the case.

So I've chosen to rewrite this PR just skipping all the bookkeeping by starting a selection whenever the LMB is pressed. Based on my testing this solves the issue and doesn't introduce any regressions, however I'd happily accept other testers because I'm not quite sure why this was done the way it has been done.

It's probably also a good idea to wait for @jwilm before merging this. Since he wrote the code he's probably best informed about the potential pitfalls with my approach.

**Comment by chrisduerr** [comment]
Since this branch had significant merge conflicts with the master (basically everything that was change), I've opted to just reimplement the changes on top of the latest master instead of rebasing and fixing the conflict.

Everything seems to be working well, however I am not able to reproduce the original issue on my main machine since it reports events too quickly. I'll try to test it on my laptop tomorrow, but any feedback is appreciated.
