### PR TITLE
Fix Selection While Scrolling

### LINKED ISSUE #1598: Update selection when scrolling
When scrolling in Alacritty with an active selection, the selection will not update until the mouse cursor is moved.

The expected behavior would be that after scrolling, the selection would update itself to go right to the new position of the mouse cursor while the primary mouse button is held down.

This affects both normal scrolling in the scrollback buffer and scrolling inside of Applications like `man` using the faux scrolling feature.

### PR DESCRIPTION
**Pull request by nixpulvis**
Properly update an active selection while scrolling the main scrollback buffer.

- [x] Standard scrolling support
- [x] Rebase down to three commits (cell_side update, standard scrolling, changelog)
- ~Faux scrolling support~ succeeded by #1644 and #1640 (possibly)

Fixes #1598.

### CODE REVIEW

File: src/event.rs [hunk 1]
```diff
@@ -58,6 +58,23 @@ impl<'a, N: Notify + 'a> input::ActionContext for ActionContext<'a, N> {
...
+        let report_mode = TermMode::MOUSE_REPORT_CLICK | motion_mode;
+        if self.mouse().left_button_state == ElementState::Pressed &&
+            (modifiers.shift || !self.terminal_mode().intersects(report_mode))
+        {
+            let cell_side = self.get_mouse_side();
+            self.update_selection(Point {
+                line: point.line,
+                col: point.col
+            }, cell_side);
+        }
```
Comment (chrisduerr) [inline src/event.rs]: Since we should have access to the selection on the terminal from the `scroll` method, it should be possible to skip the check for mouse button states and terminal modes etc.

You could check if a selection is present, but since that is already checked in the `update_selection` method, it would probably be sufficient for functionality if you just call the `update_selection` method without checking for anything.

**Comment by nixpulvis** [comment]
Ok, just need to dive into faux scrolling now I think.

File: src/event.rs [hunk 2]
```diff
@@ -58,6 +58,15 @@ impl<'a, N: Notify + 'a> input::ActionContext for ActionContext<'a, N> {
...
         self.terminal.scroll_display(scroll);
+
+        let (x, y) = (self.mouse().x, self.mouse().y);
+        let size_info = self.size_info();
+        let point = size_info.pixels_to_coords(x, y);
+        let cell_side = self.mouse().cell_side;
+        self.update_selection(Point {
+            line: point.line,
+            col: point.col
+        }, cell_side);
```
Comment (chrisduerr) [inline src/event.rs]: Looking at this code, I'm questioning why we're passing line, column and cell side to the `update_selection` method. It looks like all locations where `update_selection` is called, look identical. Usually that's a good indication that it would make sense to refactor things and it shouldn't be a problem to move the code into the `update_selection` method.

Comment (nixpulvis) [reply src/event.rs]: Yep, makes a lot of sense.

**Comment by nixpulvis** [comment]
Should be done now.

**Comment by nixpulvis** [comment]
@chrisduerr should be good now I think.

**Comment by chrisduerr** [comment]
@nixpulvis Note that the cell side is already updated. This has been implemented with the URL click PR. You can actually see the code for that just a few lines right above your implementation:

https://github.com/jwilm/alacritty/blob/bd536d2c3e93c1371867ef5e30cb9ddd9aeaca8b/src/input.rs#L346
