### PR TITLE
Fix scrollback accessing indices out of bounds

### LINKED ISSUE #1400: Scrollback attempting to access index out of bounds
rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
Linux t470 4.17.0-2-MANJARO #1 SMP PREEMPT Fri Jun 8 07:13:17 UTC 2018 x86_64 GNU/Linux
alacritty @ scrollback / bfd62ef

from time to time I get random crashes on scrollback when there is a lot of text put out very fast.

I managed to get a backtrace by running cppcheck --enable=all --inconclusive --debug --verbose -j 4 on the llvm repo which made alacritty crash one time:

````
thread 'main' panicked at 'assertion failed: requested < self.inner.len()', src/grid/storage.rs:201:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: <alacritty::grid::storage::Storage<T>>::compute_index
             at src/grid/storage.rs:201
   7: <alacritty::grid::storage::Storage<T> as core::ops::index::Index<usize>>::index
             at src/grid/storage.rs:285
   8: <alacritty::grid::Grid<T> as core::ops::index::Index<usize>>::index
             at src/grid/mod.rs:512
   9: <alacritty::grid::GridIterator<'a, T> as core::iter::iterator::Iterator>::next
             at src/grid/mod.rs:471
  10: <alacritty::term::Term as alacritty::selection::SemanticSearch>::semantic_search_right
             at src/term/mod.rs:63
  11: alacritty::selection::Selection::span_semantic
             at src/selection.rs:181
  12: alacritty::selection::Selection::to_span
             at src/selection.rs:158
  13: alacritty::term::Term::selection_to_string
             at src/term/mod.rs:980
  14: <alacritty::event::ActionContext<'a, N> as alacritty::input::ActionContext>::copy_selection
             at ./src/event.rs:62
  15: <alacritty::input::Processor<'a, A>>::on_mouse_release
             at ./src/input.rs:454
  16: <alacritty::input::Processor<'a, A>>::mouse_input
             at ./src/input.rs:559
  17: <alacritty::event::Processor<N>>::handle_event
             at ./src/event.rs:312
  18: <alacritty::event::Processor<N>>::process_events::{{closure}}
             at ./src/event.rs:421
  19: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &'a mut F>::call_mut
             at /checkout/src/libcore/ops/function.rs:261
  20: winit::platform::platform::x11::EventsLoop::process_event
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.0/src/platform/linux/x11/mod.rs:670
  21: winit::platform::platform::x11::EventsLoop::poll_events
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.0/src/platform/linux/x11/mod.rs:212
  22: winit::platform::platform::EventsLoop::poll_events
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.0/src/platform/linux/mod.rs:467
  23: winit::EventsLoop::poll_events
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.0/src/lib.rs:225
  24: alacritty::window::Window::poll_events
             at ./src/window.rs:280
  25: <alacritty::event::Processor<N>>::process_events
             at ./src/event.rs:435
  26: alacritty::run
             at src/main.rs:179
  27: alacritty::main
             at src/main.rs:62
  28: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  29: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  30: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  31: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  32: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  33: main
  34: __libc_start_main
  35: _start
````

### LINKED ISSUE #1406: Semantic selection behaving unexpectedly with wrapped lines on scrollback
I've noticed an interesting behavior with semantic selection in combination with linewraps. This issue consists of these two problems:

#### Live selection updating

Every time the user scrolls in the scrollback PR, the semantic selection is re-calculated. This leads to selection changing in combination with the problems caused by other issues.
This shouldn't be a huge issue though, but searching for semanatic escapes every time the user scrolls doesn't seem like a great idea for performance.

#### Selection across viewport borders

When the first line in the viewport is a line which wrapped from the previous line (which is outside of the viewport), the selection itself only goes to the beginning of the line, instead of wrapping to the line outside of the viewport. This can be observed by pasting the selection made. As soon as the user scrolls up now, the selection is updated.

#### Selection off-by-one
When double-clicking the last `e` in `"teee[...]est"`, the selection is displayed correctly (`teee[...]est`), however the text copied is `teee[...]est"`. This is only a problem whith linewraps, it doesn't happen if the word is a single line. The viewport is irrelevant here.

### PR DESCRIPTION
**Pull request by chrisduerr**
There have been two instances of the scrollback trying to access indices
which were moved out of bounds due to new lines (`yes` command). These
have both been fixed.

The first instance was during semantic selection, since the logic of
limiting the selection start point was moved outside of `compute_index`,
it was necessary to add this to semantic selection too. Now semantic
selection, line selection and normal selection should all work without
crashing when new lines are shoving the selection out of bounds.

The other error was with the viewport being outside of the scrollback
history. Since the default is to keep the scrollback buffer at its
current position when new lines are added, it is possible that the
position the scrollback buffer is at is suddenly shoved out of the
visible area. To fix this the `display_offset` is now limited to always
be an allowed value.
If a single line of the viewport is moved out of the history now, the
viewport should move down a single line now, so only valid content is
displayed, with multiple lines this process is repeated.

This fixes #1400 and also fixes #1406.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Gave it a quick spin, looks good to me :)

**Comment by nixpulvis** [comment]
I can crash this branch by doubleclicking on `yes` output while it's running.

**Comment by matthiaskrgr** [comment]
Hm this looks like the backtrace I previously got https://github.com/jwilm/alacritty/issues/1400#issue-337219794
Are you sure everything went right on your side?

**Comment by chrisduerr** [comment]
@nixpulvis Could you double-check that you're on the latest version of this PR and then send me the stacktrace if the issue is still present?

**Comment by chrisduerr** [comment]
Please share the full stacktrace using `RUST_BACKTRACE=1 cargo run`. That will probably solve this rather quickly!

**Comment by nixpulvis** [comment]
Here you go.

**Full stacktrace:**
<details>
```
thread 'main' panicked at 'assertion failed: requested < self.len', src/grid/storage.rs:201:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:397
   6: <alacritty::grid::storage::Storage<T>>::compute_index
             at src/grid/storage.rs:201
   7: <alacritty::grid::storage::Storage<T> as core::ops::index::Index<usize>>::index
             at src/grid/storage.rs:285
   8: <alacritty::grid::Grid<T> as core::ops::index::Index<usize>>::index
             at src/grid/mod.rs:515
   9: <alacritty::grid::GridIterator<'a, T> as alacritty::grid::BidirectionalIterator>::prev
             at src/grid/mod.rs:489
  10: <alacritty::term::Term as alacritty::selection::SemanticSearch>::semantic_search_left
             at src/term/mod.rs:49
  11: alacritty::selection::Selection::span_semantic
             at src/selection.rs:181
  12: alacritty::selection::Selection::to_span
             at src/selection.rs:158
  13: alacritty::term::Term::renderable_cells::{{closure}}
             at src/term/mod.rs:1075
  14: <core::option::Option<T>>::and_then
             at /checkout/src/libcore/option.rs:612
  15: alacritty::term::Term::renderable_cells
             at src/term/mod.rs:1074
  16: alacritty::display::Display::draw::{{closure}}
             at src/display.rs:373
  17: alacritty::renderer::QuadRenderer::with_api
             at src/renderer/mod.rs:658
  18: alacritty::display::Display::draw
             at src/display.rs:365
  19: alacritty::run
             at src/main.rs:204
  20: alacritty::main
             at src/main.rs:62
  21: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  24: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  25: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  26: main
  27: __libc_start_main
  28: _start
```
</details>

Running a `git bisect` shows f895ba954cef6c0efbcb5b2687f98eed8bcbdea7 as the introduction of this issue, FWIW.

**Comment by chrisduerr** [comment]
@nixpulvis if you wouldn't mind debugging this further, since I can't reproduce this, I'd be interested in a few debug outputs.

If you want to look into this, could you apply this patch and give me the output of it upon crash? It should output `POINT: ...` a bunch of times, I'm just interested in the last time before the crash and the `REQUESTED: ...` output

**Comment by nixpulvis** [comment]
Copying the whole output just for completeness sake. Here's what I get when I apply the patch, run `yes` and double click.

FWIW, it's important to double click **on a y** (or whatever you're yesing), otherwise it doesn't crash, but just starts printing a lot of `POINT: Point { line: 10047, col: Column(10) }, BOT: 0, TOP: 47`.

File: src/grid/mod.rs [hunk 1]
```diff
@@ -479,7 +474,7 @@ impl<'a, T> BidirectionalIterator for GridIterator<'a, T> {
         let num_cols = self.grid.num_cols();
 
         match self.cur {
-            Point { line, col: Column(0) } if line == self.top => None,
+            Point { line, col: Column(0) } if line == self.grid.len() - 1 => None,
```
Comment (chrisduerr) [inline src/grid/mod.rs]: I've changed the `prev()` and `next()` iterators to iterate over the complete grid here, it seems like this works (tests don't fail) and for everything else the DisplayIterator should be used. However there's probably a good reason why this has been done this way, can you maybe elaborate on this @jwilm?

**Comment by nixpulvis** [comment]
Working for me now :tada:

File: src/grid/mod.rs (hunk 1 above)
Comment (jwilm) [reply src/grid/mod.rs]: Looks like a bug :man_shrugging:

Comment (jwilm) [reply src/grid/mod.rs]: `self.top` was used to avoid extra conversions of the form `Line -> usize`. Is it possible that we can do a bounds check when selection is active without needing to change this code?

Comment (chrisduerr) [reply src/grid/mod.rs]: It's possible, but the behavior of this code seems faulty to me. The iterator over the raw grid shouldn't stop as soon as it hits the viewport boundary, should it? Based on my understanding the viewport should be irrelevant for selection.

Also semantic selection is the only consumer of `prev()`, just `next()` is re-used in multiple places.

Comment (jwilm) [reply src/grid/mod.rs]: Oh yeah, that sounds right. I'm starting to confuse myself with the different iterators we have which aren't clear about what they are supposed to provide. In some cases, we have something like a `GridViewportIterator` which isn't named as such.

Anyway, sounds like you have the right idea here.

Comment (nixpulvis) [reply src/grid/mod.rs]: FWIW, termite allows semantic selections to span above the viewport, for example when a URL is broken onto two lines.

Comment (chrisduerr) [reply src/grid/mod.rs]: I'll probably run a round of benchmarks just to make sure there wasn't some performance reason for doing things the way they are done right now, that should help provide an additional bit of safety.

**Comment by chrisduerr** [comment]
I've benchmarked this PR just to make sure that the changes to the iterators would not have any negative effect and I wasn't able to measure any regressions, so this looks good to me.
