### PR TITLE
src/grid/storage.rs: fix 32-bit compability

### LINKED ISSUE #1552: Error compiling on Ubuntu 32 bit
Which operating system does the issue occur on?
Ubuntu 18.04

If on linux, are you using X11 or Wayland?
X11

$ rustc --version
rustc 1.29.0 (aa3ca1994 2018-09-11)

And I have installed [extra libraries](https://github.com/jwilm/alacritty#debianubuntu-1).
```shell
 Running `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=1 --cfg 'feature="default"' -C metadata=5ee2b18ca4c9524a -C extra-filename=-5ee2b18ca4c9524a --out-dir /home/dikiaap/.local/src/alacritty/target/release/deps -L dependency=/home/dikiaap/.local/src/alacritty/target/release/deps --extern arraydeque=/home/dikiaap/.local/src/alacritty/target/release/deps/libarraydeque-08ee37e97b90e418.rlib --extern base64=/home/dikiaap/.local/src/alacritty/target/release/deps/libbase64-e6eabaf53e7cc438.rlib --extern bitflags=/home/dikiaap/.local/src/alacritty/target/release/deps/libbitflags-b0c8b66076b97148.rlib --extern cgmath=/home/dikiaap/.local/src/alacritty/target/release/deps/libcgmath-0d8067f9268911f7.rlib --extern clap=/home/dikiaap/.local/src/alacritty/target/release/deps/libclap-f307362568949e59.rlib --extern copypasta=/home/dikiaap/.local/src/alacritty/target/release/deps/libcopypasta-58ada58588ce64e6.rlib --extern env_logger=/home/dikiaap/.local/src/alacritty/target/release/deps/libenv_logger-e6fd71e176733754.rlib  --extern errno=/home/dikiaap/.local/src/alacritty/target/release/deps/liberrno-6dfd0d62082eba63.rlib --extern fnv=/home/dikiaap/.local/src/alacritty/target/release/deps/libfnv-c908a0dca541167d.rlib --extern font=/home/dikiaap/.local/src/alacritty/target/release/deps/libfont-258430fbd2fcb0f6.rlib --extern glutin=/home/dikiaap/.local/src/alacritty/target/release/deps/libglutin-af341f60b8b6fa52.rlib --extern libc=/home/dikiaap/.local/src/alacritty/target/release/deps/liblibc-e3c5af6976bd5979.rlib --extern log=/home/dikiaap/.local/src/alacritty/target/release/deps/liblog-772ee7f320a2bec5.rlib --extern mio=/home/dikiaap/.local/src/alacritty/target/release/deps/libmio-2d18fd33b3c7d7e0.rlib --extern mio_more=/home/dikiaap/.local/src/alacritty/target/release/deps/libmio_more-684d665528f741d7.rlib --extern notify=/home/dikiaap/.local/src/alacritty/target/release/deps/libnotify-5951ca4b812defa2.rlib --extern parking_lot=/home/dikiaap/.local/src/alacritty/target/release/deps/libparking_lot-27fbe5ef26366209.rlib --extern serde=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde-80a63e587b7907f5.rlib --extern serde_derive=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_derive-46c4171b1916aa33.so --extern serde_json=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_json-eefe52ccde8f9d85.rlib --extern serde_yaml=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_yaml-7b75d4a36d5d8bec.rlib --extern static_assertions=/home/dikiaap/.local/src/alacritty/target/release/deps/libstatic_assertions-ba749e4bb42cac79.rlib --extern unicode_width=/home/dikiaap/.local/src/alacritty/target/release/deps/libunicode_width-f17deb847f8d49c1.rlib --extern vte=/home/dikiaap/.local/src/alacritty/target/release/deps/libvte-c41d051770f3056c.rlib --extern x11_dl=/home/dikiaap/.local/src/alacritty/target/release/deps/libx11_dl-8c327cb4bfebebf0.rlib --extern xdg=/home/dikiaap/.local/src/alacritty/target/release/deps/libxdg-040b08a04276b707.rlib -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/home/dikiaap/.local/src/alacritty/target/release/build/libloading-4e622ceb383faa3e/out`

error[E0512]: transmute called with types of different sizes
   --> src/grid/storage.rs:226:9
    |
226 |         assert_eq_size!(Row<T>, [u32; 8]);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: grid::row::Row<T> (128 bits)
    = note: target type: [u32; 8] (256 bits)
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0512`.
error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=1 --cfg 'feature="default"' -C metadata=5ee2b18ca4c9524a -C extra-filename=-5ee2b18ca4c9524a --out-dir /home/dikiaap/.local/src/alacritty/target/release/deps -L dependency=/home/dikiaap/.local/src/alacritty/target/release/deps --extern arraydeque=/home/dikiaap/.local/src/alacritty/target/release/deps/libarraydeque-08ee37e97b90e418.rlib --extern base64=/home/dikiaap/.local/src/alacritty/target/release/deps/libbase64-e6eabaf53e7cc438.rlib --extern bitflags=/home/dikiaap/.local/src/alacritty/target/release/deps/libbitflags-b0c8b66076b97148.rlib --extern cgmath=/home/dikiaap/.local/src/alacritty/target/release/deps/libcgmath-0d8067f9268911f7.rlib --extern clap=/home/dikiaap/.local/src/alacritty/target/release/deps/libclap-f307362568949e59.rlib --extern copypasta=/home/dikiaap/.local/src/alacritty/target/release/deps/libcopypasta-58ada58588ce64e6.rlib --extern env_logger=/home/dikiaap/.local/src/alacritty/target/release/deps/libenv_logger-e6fd71e176733754.rlib --extern errno=/home/dikiaap/.local/src/alacritty/target/release/deps/liberrno-6dfd0d62082eba63.rlib --extern fnv=/home/dikiaap/.local/src/alacritty/target/release/deps/libfnv-c908a0dca541167d.rlib --extern font=/home/dikiaap/.local/src/alacritty/target/release/deps/libfont-258430fbd2fcb0f6.rlib  --extern glutin=/home/dikiaap/.local/src/alacritty/target/release/deps/libglutin-af341f60b8b6fa52.rlib --extern libc=/home/dikiaap/.local/src/alacritty/target/release/deps/liblibc-e3c5af6976bd5979.rlib --extern log=/home/dikiaap/.local/src/alacritty/target/release/deps/liblog-772ee7f320a2bec5.rlib --extern mio=/home/dikiaap/.local/src/alacritty/target/release/deps/libmio-2d18fd33b3c7d7e0.rlib --extern mio_more=/home/dikiaap/.local/src/alacritty/target/release/deps/libmio_more-684d665528f741d7.rlib --extern notify=/home/dikiaap/.local/src/alacritty/target/release/deps/libnotify-5951ca4b812defa2.rlib --extern parking_lot=/home/dikiaap/.local/src/alacritty/target/release/deps/libparking_lot-27fbe5ef26366209.rlib --extern serde=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde-80a63e587b7907f5.rlib --extern serde_derive=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_derive-46c4171b1916aa33.so --extern serde_json=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_json-eefe52ccde8f9d85.rlib --extern serde_yaml=/home/dikiaap/.local/src/alacritty/target/release/deps/libserde_yaml-7b75d4a36d5d8bec.rlib --extern static_assertions=/home/dikiaap/.local/src/alacritty/target/release/deps/libstatic_assertions-ba749e4bb42cac79.rlib --extern unicode_width=/home/dikiaap/.local/src/alacritty/target/release/deps/libunicode_width-f17deb847f8d49c1.rlib --extern vte=/home/dikiaap/.local/src/alacritty/target/release/deps/libvte-c41d051770f3056c.rlib --extern x11_dl=/home/dikiaap/.local/src/alacritty/target/release/deps/libx11_dl-8c327cb4bfebebf0.rlib --extern xdg=/home/dikiaap/.local/src/alacritty/target/release/deps/libxdg-040b08a04276b707.rlib -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/usr/lib/i386-linux-gnu -L native=/home/dikiaap/.local/src/alacritty/target/release/build/libloading-4e622ceb383faa3e/out` (exit code: 1)
```

### PR DESCRIPTION
**Pull request by jnbr**
Use usize instead of u64 to fix 32-bit builds.

This fixes #1552.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Thanks for sending this PR!

There is some issue with this PR, since it still exposes the same behavior on 64 bit, however it needs to be changed, since the size of `Row<T>` is different. I can't test 32bit myself, but this should cause issues on 32bit systems.

I'm currently working on a PR for this myself. I'd love some testing if you have a 32 bit machine.

**Comment by chrisduerr** [comment]
I've fixed the issue I've mentioned, everything's looking good now from my perspective.

Waiting for @jwilm to take another look though, since there's a lot of complexity in this tiny code snippet.

**Comment by jnbr** [comment]
I don't have a 32-bit machine which is capable of running alacritty.

> There is some issue with this PR, since it still exposes the same behavior on 64 bit, however it needs to be changed, since the size of Row<T> is different. I can't test 32bit myself, but this should cause issues on 32bit systems.

Isn't this covered by different size of `usize` already?

**Comment by chrisduerr** [comment]
It is not. Since the `0..4` was hardcoded in the existing version.

It basically copies everything one qword at a time. However since the sizes are different on 64 and 32 bit, this means that it's 3 qwords on 32 bit systems and 4 on 64 bit. So it's required to do `0..3` on 32 bit.

This could all be done through conditional compilation, since it's possible to check the pointer size. However what my code does is checking the size of the `Row<T>`, which will be the size of a `Vec` plus the size of `usize` and then check how many qwords fit into it (each qword is 8 bytes, that's where the `/ 8` comes from. So while iterating it's automatically split up into qword-sized chunks and these chunks then are copied.

If you're wondering why this is necessary, the comments in this specific code section should help out. This is done as an optimization because the compiler doesn't recognize this is possible.

**Comment by jnbr** [comment]
I suspect a misunderstanding here.
From https://doc.rust-lang.org/std/primitive.usize.html:
> The size of this primitive is how many bytes it takes to reference any location in memory. For example, on a 32 bit target, this is 4 bytes and on a 64 bit target, this is 8 bytes.

`Row<T>`  is always the size of `4 * sizeof(usize)`. This is asserted in line 226: `assert_eq_size!(Row<T>, [usize; 4]); `

The size of `usize` or qword is architecture dependant. The amount of usize / qword fields is not.

**Comment by chrisduerr** [comment]
Thanks for the feedback.

Looking at the code, it's true that using offsets of `usize`, this should require the same number of steps on 32 bit as on 64 bit. And as such my commit should break things. Would be nice to have someone with 32 bit computer confirm that my commit doesn't work and the previous one does though.

However this means it doesn't split it by QWORDs anymore. While WORDs vary in size based on architecture, DWORDs and QWORDs have a fixed size afaik. So the comments might have to be changed to indicate that it doesn't split by QWORDs on 32 bit.

In the original change I've made, I kept the sizes as `u64`, so that should make it work too, just the combination of the two changes shouldn't work out.

**Comment by dikiaap** [comment]
I'm using the last commit. It was was successfully compiled and work when running Alacritty

File: src/grid/storage.rs [hunk 1]
```diff
@@ -232,14 +232,14 @@ impl<T> Storage<T> {
...
+            let a_ptr = self.inner.as_mut_ptr().add(a) as *mut usize;
+            let b_ptr = self.inner.as_mut_ptr().add(b) as *mut usize;
 
             // Copy 1 qword at a time
             //
             // The optimizer unrolls this loop and vectorizes it.
-            let mut tmp: u64;
-            for i in 0..4 {
+            let mut tmp: usize;
+            for i in 0..(::std::mem::size_of::<Row<T>>() as isize / 8) {
```
Comment (jwilm) [inline src/grid/storage.rs]: Let's change this back to 4 since we assert above there are 4 `usize` and we are moving `usize` around.

**Comment by chrisduerr** [comment]
Looks good to me now and since jwilm doesn't seem to have any other complaints, this should resolve 32 bit build issues.
