### PR TITLE
Optimize indexing of the grid's raw buffer

### LINKED ISSUE #1316: Performance regression in scrollback
I've just tested the scrollback PR because I wanted to make sure that scrolling is still faster than on master, and it is. However, while testing it I've noticed that there were some significant regressions comparing current master to the scrollback PR.

Test Results:

| Test | Master | Scrollback |
| - | - | - |
| scrolling | 6s | 4.4s |
| alt-screen-random-write | 8.5s | 12s |
| scrolling-in-region | 4s | 13s |

These tests are based on https://github.com/jwilm/alacritty.

I'm not sure why I haven't noticed this earlier, but it seems like these regressions have been present ever since the scrollback PR was created. Especially the regression in `scrolling-in-region` seems quite massive.

These results were captured on X11/i3/compton/amd/mesa.

### PR DESCRIPTION
**Pull request by chrisduerr**
The `compute_index` method in the `Storage` struct used to normalize
indices was responsible for a significant amount of the CPU time spent
while running the `alt-screen-random-write` benchmark (~50%).

The issue with this relatively simple method was that due to how often
the method is executed, the modulo operation was too expensive. However
since most of the time when a majority of the buffer changes (high
througput), it's in the alternate screen, the modulo operation can be
skipped with a simple branch. There might be some more optimization to
be done here, however this resolved all measurable issues in the
`alt-sceen-random-write` benchmark.

The whole `vtebench` suite hasn't been tested, however unless there were
some regressions, this fixes #1316. I will benchmark this a bit more in
the near future.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Here are the benchmarking results vs the master branch:

| Benchmark | Master | PR | Scrollback |
|-|-|-|-|
| alt-screen-random-write | 4.204 | 5.149 | 7.315 |
| scrolling | 7.551 | 3.849 | 4.362 |
| scrolling-in-region | 7.480 | 3.927 | 4.342 | 
| scrolling-in-region (50) | 3.866 | 3.949 | 15.755 |

Notable here is that in the `alt-screen-random-write` benchmark the performance has been dramatically improved, it's definitely not up to par with master yet and `perf` is still showing some hotspots that could definitely be tweaked, but it's a significant boost.

Scrolling and scrolling-in-region show the same benefits that they've shown on the scrollback branch for a long time, there's a little improvement in both but that's within a margin of error. There definitely hasn't been any regression there though, which is nice.

The scrolling-in-region benchmark with 50 lines from the bottom is probably the biggest surprise here, I never intended to improve its performance but it seems like the changes introduced here add some incredible performance boost to this benchmark. Even though I'm not sure if there's any real world application for this benchmark, the huge boost in performance is definitely a surprise I'm very happy about. :)

**Comment by nixpulvis** [comment]
I'm having trouble replicating this speedup, both the scrollback branch, and you're scrollback branch are reporting the same numbers for the scrolling-in-region 50 test. Both however are roughly the same as master.

**Comment by chrisduerr** [comment]
@nixpulvis How did you run the test? Using `--lines-from-bottom 50`? If your terminal is too small, it's possible that 50 might actually be too big, so you'll have to configure a value yourself where a majority of the screen doesn't scroll.

Either way the main focus of this PR for me was the alt-screen-random-write benchmark. However if scrolling-in-region 50 has always been as fast as master on your machine, I'd be surprised but in the best possible way. So that's not a bad thing. :D

**Comment by chrisduerr** [comment]
This actually shouldn't be merged yet. I think we can make sure that `self.zero` is ***always*** smaller than `self.inner.len()`, currently that's not the case yet because it's set to `self.inner.len()` once, but that can just be replaced to `0`, the only other time it is bigger than `self.inner.len()` is when a selection is made which leaves the buffer (select while runnig `yes` for example). I'm not quite sure how I'd handle this yet, but I'm looking into it.

**Comment by chrisduerr** [comment]
I've changed it up a bit. So now instead of just accepting that the worst case is using a modulo operation, a modulo is never used. This shouldn't increase/decrease performance in any way, but is rather used to make it a little more clear what's actually going on and which edge-cases are being handled.

I think this is the better solution even though it might require a few more changes.

File: src/grid/storage.rs [hunk 1]
```diff
@@ -200,8 +197,19 @@ impl<T> Storage<T> {
     }
 
     /// Compute actual index in underlying storage given the requested index.
-    fn compute_index(&self, requested: usize) -> usize {
-        (requested + self.zero) % self.inner.len()
+    fn compute_index(&self, mut requested: usize) -> usize {
+        // If line outside the buffer is requested, return the last line in the buffer
```
Comment (jwilm) [inline src/grid/storage.rs]: Could we just `assert!` on this condition rather than using `min`? This would force us to improve bookkeeping elsewhere, but it would potentially allow this method to be further optimized.

Comment (chrisduerr) [reply src/grid/storage.rs]: Yeah I've thought about that. My intention for now was to keep things the way they are, however this could definitely cause issues if anyone else is trying to request a size which is too big (at least this might cause silent failure, or failure at the wrong location).

I'm all for changing this though, however the performance part of it shouldn't be an issue. Currently this is not a problem at all and It's not a super slow way to achieve this either, so I wouldn't do it for the performance but rather because it feels a bit more like the "proper" way to do things.

Which just leaves the question if selection should be completely cancelled or if selection should go up to the last line in the buffer. I'm all for keeping the behavior it is right now and making it go to the last line of the buffer. I don't think there's any issue with selection potentially returning an "incorrect" result, so something's better than nothing I'd say.

Comment (chrisduerr) [reply src/grid/storage.rs]: Done! Seems to work out well. Decided to go for a `debug_assert` just to make sure there's no unnecessary slowdowns in release mode.
