### PR TITLE
Fix scrollback history size 0 bug

### LINKED ISSUE #1150: Should be able to set scrollback history to zero to disable it.
I am not sure if this works, but it should certainly be tested and fixed as needed.

### PR DESCRIPTION
**Pull request by chrisduerr**
There was an issue where alacritty would panic whenever the scrollback
history size is set to 0, this fixes that issue.

The panic was caused by a substraction with unsigned integers which was
underflowing, this has been fixed to use `saturating_sub`.

After that was fixed there was still a bug where scrollback would not
behave correctly because the number of lines in the grid was decided at
startup.
This has been adapted so whenever the size of the terminal changes, the
scrollback history and grid adapts to make sure the number of lines in
the terminal is always the number of visible lines plus the amount of
scrollback lines configured in the config file.

This fixes #1150.

### CODE REVIEW

File: src/grid/mod.rs [hunk 1]
```diff
@@ -240,6 +243,13 @@ impl<T: Copy + Clone> Grid<T> {
         self.raw.set_visible_lines(new_line_count);
         self.lines = new_line_count;
 
+        // Fill up the history with empty lines
+        if self.raw.len() < self.raw.capacity() {
+            for _ in self.raw.len()..self.raw.capacity() {
+                self.raw.push(Row::new(self.cols, &template));
+            }
+        }
```
Comment (nixpulvis) [inline src/grid/mod.rs]: Correct me if I'm wrong but this is a temparary solution until we have a buffer that grows and shrinks with the needed size. See #1236

**Comment by chrisduerr** [comment]
Currently there still is an issue where growing/shrinking the terminal will lead to the current lines of it getting mixed up.

That should probably be fixed before this is merged.

**Comment by chrisduerr** [comment]
It seems like there already is some code which clears the content of the history after shrinking. Do you know something about this @jwilm? It probably will not be needed anymore after this PR is merged.

**Comment by chrisduerr** [comment]
Everything should be good now, any feedback @jwilm?

These changes have been introduced:
```
There was an issue where the lines would be messed up when the terminal
was resized, this was because lines were just added/removed at the end
of the buffer instead of the actual end of the terminal (since the end
of the terminal might be in the middle of the buffer).

This has been fixed by relying on `self.zero` to determine the position
of the start of the terminal and then calculating where lines have to be
inserted/removed.

Some tests have also been added with documentation that should make it
a little easier to understand how the process works and how the raw
buffer is layed out.

This should all work no matter how big the scrollback history and even
when the currenty viewport is not at the bottom of the terminal output.
```
