### PR TITLE
Touchpad scroll fix (do not merge!)

### LINKED ISSUE #721: Touchpad scrolling is janky
I don't know exactly what's going on, but when I scroll with the touchpad it requires me to scroll a lot before it will even register, and then it scrolls a ton at once.

### PR DESCRIPTION
**Pull request by lheckemann**
This is an RFC PR to fix #721, my first attempt at modifying a Rust application that people use and my first foray into Alacritty's code. As such there are a few issues with how it's implemented — I'm not happy with how the scrolling state is duplicated across `event::Processor` and `input::ActionContext` (although this might be appropriate?), the names I've used are terrible and I've added a dumb implementation of the state function to what is as far as I can tell a stub implementation of `ActionContext` for testing purposes. I'd love to get some feedback on where this stuff should go and what it should look like!

### CODE REVIEW

**Comment by maximbaz** [comment]
Just so that you know, the fix itself works great, scrolling is smooth 🎉

**Comment by lheckemann** [comment]
@jwilm ping?

File: src/event.rs [hunk 1]
```diff
@@ -386,6 +396,7 @@ impl<N: Notify> Processor<N> {
 
             // Scope needed to that hide_cursor isn't borrowed after the scope
             // ends.
+            let mut scrolled_lines = 0.0;
```
Comment (jwilm) [inline src/event.rs]: Instead of starting from zero every time scroll events arrive, we should try and persist it. We might want this if we end up supporting smooth visual scrolling, and it may actually affect behavior regardless.

One option would be putting the `scrolled_lines` property onto the mouse state struct.

File: src/event.rs [hunk 2]
```diff
@@ -40,6 +40,7 @@ pub struct ActionContext<'a, N: 'a> {
     pub received_count: &'a mut usize,
     pub suppress_chars: &'a mut bool,
     pub last_modifiers: &'a mut ModifiersState,
+    pub _scrolled_lines: f32,
```
Comment (jwilm) [inline src/event.rs]: In Rust, leading member names with a `_` indicates that the value is unused. If you want to indicate visibility, that's done with the `pub` qualifier (or lack thereof).

File: src/input.rs [hunk 3]
```diff
@@ -352,13 +353,15 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
 
         match delta {
             MouseScrollDelta::LineDelta(_columns, lines) => {
-                let code = if lines > 0.0 {
+                let to_scroll = self.ctx.lines_to_scroll(lines);
+
+                let code = if to_scroll > 0 {
```
Comment (jwilm) [inline src/input.rs]: We should handle the case where `to_scroll` is zero lines.

File: src/event.rs [hunk 4]
```diff
@@ -126,6 +127,12 @@ impl<'a, N: Notify + 'a> input::ActionContext for ActionContext<'a, N> {
     fn last_modifiers(&mut self) -> &mut ModifiersState {
         &mut self.last_modifiers
     }
+
+    fn lines_to_scroll(&mut self, lines: f32) -> i32 {
```
Comment (jwilm) [inline src/event.rs]: It might make more sense to put this method on the input processor so the logic can be reused with different `ActionContext`.

**Comment by lheckemann** [comment]
Thanks for the feedback! "mouse state struct" was the key, it's much much neater now :)

**Comment by jwilm** [comment]
Thanks @lheckemann!
