### PR TITLE
Fixing panic on cat /dev/urandom

### LINKED ISSUE #63: running `cat /dev/urandom` crashes alacritty
As the title says, running `cat /dev/urandom` consistently crashes alacritty. Apparently some random escape codes send it into a state where this condition is triggered: https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L634. Here is a log with backtrace: https://linx.li/aomx2zxa.ext

Great project btw, good luck! :)

### PR DESCRIPTION
**Pull request by mbrumlow**
- Checks to make sure lines count coming from the pty are within a proper
range before doing scrolling.

- Sanitizes scroll region when being set.

- Changes panic for unimplemented screen clear to a print statement.

The first two changes ensure scrolling won't crash us. By sanitizing the
region on set we don't have to complicate the scroll code with limits,
mins, or maxes to ensure the scroll operation is within the range.
Checking if the lines is greater than the total region allows us to
simply clear the region and avoid subtracting large numbers from small
ones.

Fixes #63

### CODE REVIEW

File: src/term/mod.rs [hunk 1]
```diff
@@ -968,7 +980,7 @@ impl ansi::Handler for Term {
                 self.grid.clear(|c| c.reset(&template));
             },
             _ => {
-                panic!("ansi::ClearMode::Above not implemented");
+                println!("ansi::ClearMode::Above not implemented");
```
Comment (jwilm) [inline src/term/mod.rs]: Should be err_println

File: src/term/mod.rs [hunk 2]
```diff
@@ -506,7 +506,7 @@ impl Term {
         // Scroll up to keep cursor and as much context as possible in grid.
         // This only runs when the lines decreases.
         self.scroll_region = Line(0)..self.grid.num_lines();
-
+
```
Comment (jwilm) [inline src/term/mod.rs]: Extra spaces should be removed

Comment (mbrumlow) [inline src/term/mod.rs]: ewe, guess I don't have my editor setup to remove trailing whitespace for rust files yet. Sorry!

**Comment by mbrumlow** [comment]
Should be good now. I am off to bed for the night, so if any other changes are needed then I will get to them tomorrow (likely after work).

**Comment by jwilm** [comment]
Sounds good, and thanks!

**Comment by jwilm** [comment]
I was still getting one panic after your changes. I pushed one more change on top of them, and `cat /dev/urandom` no longer panics for me (at least within 10 minutes).
