### PR TITLE
Fix lingering window after child process exit on unix

### LINKED ISSUE #915: Quitting Vim after "alacritty -e vim" requires additional keystroke to close the terminal
If I run 

``alacritty -e vim``

And then quit right away with

``:q``

There remains a dangling Alacritty window with no text and just a cursor in the top left corner.
It persists until I move the mouse or press a key, which is a little bit annoying.
I've tested the same command with ``urxvt``, ``terminator``, ``st`` and behaviour of all seems to be the same in that they all close the terminal once ``vim`` quits.

For the record, I am writing this from Arch Linux with an i3 window manager. My server is ``X11``.

Other than that, thank you for an amazing terminal... I've been struggling to find one that takes advantage of my 144 Hz monitor, especially since I am a former FPS player and can immediately tell whether something responds to my keystrokes in 16ms or 7ms!

### LINKED ISSUE #1276: alacritty processes continue running after closing
On a fully up to date Arch Linux set up on X11 with NVIDIA proprietary driver's (396.18) and the composite extension disabled, transparency and vsync disabled (via .yml), alacritty processes continue to run and don't stop even after closing the terminal windows. My CPU cores will rise to 100% and there will be many alacritty processes running, even if you shut down the X.Org display server. I have to manually kill each alacritty process with htop for my CPU to stop maxing out at 100%.

### LINKED ISSUE #1313: Alacritty doesn't close until the first event after exiting shell
Which operating system does the issue occur on? Linux, Ubuntu 18.04

If on linux, are you using X11 or Wayland? Running Wayland with XWayland (`env WAYLAND_DISPLAY= alacritty`)

When I leave the shell with ^d or "exit", alacritty will stay alive until I do the next thing (move my mouse, click, type a character, or defocus). I'd expect it to die immediately after exiting the shell.

Screen recording of the issue: https://webmshare.com/DdYGG

glxinfo:

```console
$ glxinfo | grep OpenGL                           
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0-rc5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0-rc5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.0-rc5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

### PR DESCRIPTION
**Pull request by rkanati**
This is a crack at handing `SIGCHLD` (and conceivably others) safely and correctly, taking a different approach to #1367 by using the well-known "self-pipe trick". This should allay concerns about non- _async-signal-safe_ functions in signal handlers.

The signal handler writes received `SIG*` numbers into a pipe, which wakes up the existing I/O event loop. The loop then delegates handling back to the `Pty`, which reads the pipe, and reacts appropriately.

I'm not 100% certain on the finer points of this design, though, so I'd appreciate some feedback.

- Fixes #915
- Fixes #1276
- Fixes #1313

### CODE REVIEW

File: src/event.rs [hunk 1]
```diff
@@ -47,6 +47,7 @@ pub struct ActionContext<'a, N> {
     pub suppress_chars: &'a mut bool,
     pub last_modifiers: &'a mut ModifiersState,
     pub window_changes: &'a mut WindowChanges,
+    pub child_info: &'a tty::ChildInfo
```
Comment (rkanati) [inline src/event.rs]: `ActionContext` needs a way to get at the child PID for `spawn_new_instance`, and this seemed better than a `mut static`.

File: src/event_loop.rs [hunk 2]
```diff
@@ -343,7 +343,7 @@ impl<T> EventLoop<T>
 
             let poll_opts = PollOpt::edge() | PollOpt::oneshot();
 
-            let tokens = [1, 2];
+            let tokens = [1, 2, 3];
```
Comment (rkanati) [inline src/event_loop.rs]: Obviously we know that one token is shared for both read + write on unix, so we could use `2` for the signal pipe... but better safe than sorry, right?

File: src/event_loop.rs [hunk 3]
```diff
@@ -374,13 +374,26 @@ impl<T> EventLoop<T>
                         CHANNEL => if !self.channel_event(&mut state) {
                             break 'event_loop;
                         },
+
+                        #[cfg(unix)]
+                        token if token == self.pty.signal_token() => {
+                            let should_exit = self.pty.process_signals();
+                            if should_exit {
```
Comment (rkanati) [inline src/event_loop.rs]: Returning a `bool` here sucks, but I'm not sure what would be better.

File: src/event_loop.rs [hunk 4]
```diff
@@ -374,13 +374,26 @@ impl<T> EventLoop<T>
...
                         token if token == self.pty.read_token() || token == self.pty.write_token() => {
-                            #[cfg(unix)]
-                                {
-                                    if UnixReady::from(event.readiness()).is_hup() {
-                                        break 'event_loop;
-                                    }
+                            #[cfg(unix)] {
+                                if UnixReady::from(event.readiness()).is_hup() {
+                                    // don't try to do I/O on a dead Pty
+                                    continue;
```
Comment (rkanati) [inline src/event_loop.rs]: Not doing this caused the `pty_read` / `_write` to `EIO`, and I'm still not totally sure I've fixed that.

File: src/tty/mod.rs [hunk 5]
```diff
@@ -30,10 +30,18 @@ mod windows;
 #[cfg(windows)]
 pub use self::windows::*;
 
+/// This struct contains information about the child process.
+pub struct ChildInfo {
+    #[cfg(unix)]
+    pub pid: libc::pid_t,
+}
```
Comment (rkanati) [inline src/tty/mod.rs]: I feel like this could be useful on any platform, but since `spawn_new_instance` currently only works on 'nix anyway, I thought I'd leave it alone for now.

File: src/tty/mod.rs [hunk 6]
```diff
@@ -30,10 +30,18 @@ mod windows;
...
+
 /// This trait defines the behaviour needed to read and/or write to a stream.
 /// It defines an abstraction over mio's interface in order to allow either one
 /// read/write object or a seperate read and write object.
 pub trait EventedReadWrite {
+    // TODO: should this maybe just be called `Pseudoterminal` or `Pty`?
+    // The current attempt at generality is probably unnecessary.
```
Comment (rkanati) [inline src/tty/mod.rs]: If we dropped the pretense and had `trait Pseudoterminal` or similar, it'd feel less odd adding a `should_exit` method, which would avoid the gross `bool` on `process_signals`.

File: src/tty/unix.rs [hunk 7]
```diff
@@ -15,59 +15,79 @@
...
-static mut SHOULD_EXIT: bool = false;
-
-extern "C" fn sigchld(_a: c_int) {
-    let mut status: c_int = 0;
-    unsafe {
-        let p = libc::waitpid(PID, &mut status, WNOHANG);
-        if p < 0 {
-            die!("Waiting for pid {} failed: {}\n", PID, errno());
+/// We write any signals into the pipe, and the event loop wakes up and reads them.
+static mut SIG_PIPE_WRITE: Option<File> = None;
```
Comment (rkanati) [inline src/tty/unix.rs]: This is an `Optional` because it gets initialized when spawning the child - adding a little sync to this would probably work out nicely when we eventually get around to multiple windows (like #1589).

File: src/tty/unix.rs [hunk 8]
```diff
@@ -15,59 +15,79 @@
...
+
+unsafe extern "C" fn on_signal(sig: c_int) {
+    let old_errno = errno();
+
+    let byte = [sig as u8];
+    let file: &mut File = SIG_PIPE_WRITE.as_mut().unwrap();
+    match file.write_all(&byte) {
+        Ok(_) => {
+            // TODO: a flush is almost certainly unnecesary
+            file.flush().unwrap();
```
Comment (rkanati) [inline src/tty/unix.rs]: ...or _is it_? :thinking:

File: src/tty/unix.rs [hunk 9]
```diff
@@ -15,59 +15,79 @@
...
-/// Get the current value of errno
-fn errno() -> c_int {
-    ::errno::errno().0
+// lifted from nix::unistd (MIT)
+fn pipe() -> (File, File) {
+    unsafe {
+        let mut fds: [c_int; 2] = mem::uninitialized();
+        if let 0 = libc::pipe(fds.as_mut_ptr()) {
+            set_nonblocking(fds[0]);
+            set_nonblocking(fds[1]);
```
Comment (rkanati) [inline src/tty/unix.rs]: Non-blocking wouldn't seem to have any benefit, but _everyone_ seems to do it with self-pipes. Let me know if it's unnecessary.

File: src/tty/unix.rs [hunk 10]
```diff
@@ -185,9 +205,11 @@ fn get_pw_entry(buf: &mut [i8; 1024]) -> Passwd<'_> {
 }
 
 pub struct Pty {
+    child: Child,
     pub fd: File,
-    pub raw_fd: RawFd,
```
Comment (rkanati) [inline src/tty/unix.rs]: I took the liberty of cleaning this up - why keep this when you can `fd.as_raw_fd()`?

File: src/tty/unix.rs [hunk 11]
```diff
@@ -206,6 +228,10 @@ impl Pty {
             die!("ioctl TIOCSWINSZ failed: {}", errno());
         }
     }
+
+    pub fn child_info(&self) -> ChildInfo {
+        ChildInfo { pid: self.child.id() as _ }
+    }
```
Comment (rkanati) [inline src/tty/unix.rs]: If we turn `trait EventedReadWrite` into `trait Pty` or similar, this should either go there, or maybe come back in a tuple from `Pty::new`.

File: src/tty/unix.rs [hunk 12]
```diff
@@ -294,23 +320,28 @@ pub fn new<T: ToWinsize>(
...
-                PID = child.id() as _;
+            // Handle SIGCHLD
+            let sig_pipe_read = {
+                let (read_end, write_end) = pipe();
+                unsafe { SIG_PIPE_WRITE = Some(write_end); }
+                read_end
+            };
+
+            // TODO: replace with sigaction?
+            unsafe { libc::signal(SIGCHLD, on_signal as _) };
```
Comment (rkanati) [inline src/tty/unix.rs]: Please advise.

File: src/tty/unix.rs [hunk 13]
```diff
@@ -335,26 +366,47 @@ impl EventedReadWrite for Pty {
...
+        )?;
+
+        self.sig_token = (*token.next().unwrap()).into();
+        poll.register(
+            &EventedFd(&self.sig_pipe_read.as_raw_fd()),
+            self.sig_token,
+            mio::Ready::readable(),
+            mio::PollOpt::level()
         )
     }
```
Comment (rkanati) [inline src/tty/unix.rs]: Sticking the `register`/`reregister`/`deregister` together like this seems really gross, but I'm hard-pushed to think up a better approach.

File: src/tty/unix.rs [hunk 14]
```diff
@@ -376,6 +428,33 @@ impl EventedReadWrite for Pty {
...
+            let mut sig = [0u8];
+            self.sig_pipe_read.read_exact(&mut sig).unwrap();
+            sig[0]
+        };
+
+        match sig as i32 {
+            libc::SIGCHLD => {
+                if let Some(_) = self.child.try_wait().expect("error collecting pty child") {
+                    return true;
+                }
```
Comment (rkanati) [inline src/tty/unix.rs]: We have to be careful here to flat-out _ignore_ `SIGCHLD` from other sources, or we risk breaking anything that uses `spawn_daemon` or similar.

**Comment by rkanati** [comment]
Once this has been reviewed and tweaked, I'll squash down all those messy commits.

**Comment by chrisduerr** [comment]
Thanks a ton for the PR. Fixing this would be a huge step forward and lovely to include in the next release.

Unfortunately I'm not very familiar with signal safety, so I'll have to set aside some time to give this a proper review and test and I'm currently hung up on polishing the #2120 PR a bit.

I just wanted to let you know that this PR has not been missed and I'll definitely take a look this weekend (hopefully I can even get to it a bit earlier).

**Comment by rkanati** [comment]
Nice! No worries.

File: src/event_loop.rs (hunk 3 above)
Comment (chrisduerr) [reply src/event_loop.rs]: I'd either rename the method to something that clearly return a bool, or maybe return an enum with the type of signal that was processed? Or just an action that should be taken maybe.

File: src/tty/mod.rs (hunk 6 above)
Comment (chrisduerr) [reply src/tty/mod.rs]: I've also had issues with the name when this was initially introduced, but iirc there was a good reason for it and the naming was taken from a related API.

(See https://docs.rs/mio/0.6.16/mio/event/trait.Evented.html)

File: src/tty/unix.rs [hunk 15]
```diff
@@ -15,59 +15,79 @@
...
 
-pub fn process_should_exit() -> bool {
-    unsafe { SHOULD_EXIT }
+    set_errno(old_errno);
 }
 
-/// Get the current value of errno
-fn errno() -> c_int {
-    ::errno::errno().0
+// lifted from nix::unistd (MIT)
```
Comment (chrisduerr) [inline src/tty/unix.rs]: Why would we copy a function from a library, rather than using the library?

File: src/tty/unix.rs (hunk 7 above)
Comment (chrisduerr) [reply src/tty/unix.rs]: I feel like we should either handle a `None` value here or choose a different way to store this, otherwise I'm not sure which benefit we get from having an Option if we always crash anyways when it's `None`.

File: src/event_loop.rs (hunk 3 above)
Comment (rkanati) [reply src/event_loop.rs]: I'll try an `enum`, see how it feels.

File: src/tty/unix.rs (hunk 7 above)
Comment (rkanati) [reply src/tty/unix.rs]: It might be my weak rust-fu - I used `Option` just because it has to be initialized dynamically.

File: src/tty/unix.rs (hunk 15 above)
Comment (rkanati) [reply src/tty/unix.rs]: Because iirc we don't depend on `nix` (which is honestly kind of astounding), and I didn't want to incur something so chunky for one bugfix.

**Comment by rkanati** [comment]
I'll mess with some of these bits sometime soon. Ta!

File: src/tty/unix.rs (hunk 15 above)
Comment (chrisduerr) [reply src/tty/unix.rs]: We have an indirect dependency on nix anyways iirc. So we're pulling in one version of it anyways. Also I think in general it's the much better approach compared to copy/pasting code over, which might cause all kinds of trouble.

File: src/event_loop.rs (hunk 4 above)
Comment (rkanati) [reply src/event_loop.rs]: So, it turned out the `EIO` was actually a racy bug that's been present for who-knows-how-long, and it's a *miracle* it hasn't burnt us before - after thinking I'd screwed up somehow for a couple days, I finally reproduced it on 0.2.9. See the comments in the new code below.

File: src/tty/unix.rs (hunk 7 above)
Comment (rkanati) [reply src/tty/unix.rs]: Turns out all the alternatives are worse, currently. The only other legit way to do this on `stable` is `lazy_static!`, and that's even more overkill that `Option`.

File: src/tty/mod.rs [hunk 16]
```diff
@@ -59,6 +59,29 @@ pub trait EventedReadWrite {
...
+    #[cfg(unix)]
+    fn child_event_token(&self) -> mio::Token;
+
+    /// Tries to retrieve an event
+    ///
+    /// Returns `Some(event)` on success, or `None` if there are no events to retrieve.
+    #[cfg(unix)]
+    fn get_child_event(&mut self) -> Option<ChildEvent>;
+}
+
```
Comment (rkanati) [inline src/tty/mod.rs]: I think this is better than bloating `EventedReadWrite`, and it's free to be used by the win32 `tty` if they want to.

**Comment by rkanati** [comment]
I'm doing some finishing touches, and giving the travis instance a workout (I don't have win or mac boxes to build/test on), but hopefully this will be ready soon.

**Comment by rkanati** [comment]
Provided there are no _really_ hidden screw-ups here, I'm pretty happy with the state of this. I can make fixups or additions as requested.

File: src/tty/unix.rs (hunk 15 above)
Comment (rkanati) [reply src/tty/unix.rs]: Using `nix` now.

**Comment by rkanati** [comment]
Okay, hold up - I've been reading about `signal` vs `sigaction` and I need to switch it over. Again, sheer luck that this hasn't messed us up before.

File: src/tty/mod.rs [hunk 17]
```diff
@@ -53,6 +59,29 @@ pub trait EventedReadWrite {
...
+/// In particular, this allows for race-free child exit notification on UNIX (cf. `SIGCHLD`).
+pub trait EventedPty : EventedReadWrite {
+    #[cfg(unix)]
+    fn child_event_token(&self) -> mio::Token;
+
+    /// Tries to retrieve an event
+    ///
+    /// Returns `Some(event)` on success, or `None` if there are no events to retrieve.
+    #[cfg(unix)]
+    fn get_child_event(&mut self) -> Option<ChildEvent>;
```
Comment (chrisduerr) [inline src/tty/mod.rs]: `get_child_event` sounds like it just retrieves a field variable (like a getter), however if I understand things correctly, this is more like pulling the next event out of the PTY, right? It should probably be called something like `next_child_event` then, to represent that calling it twice in quick succession usually never returns the same value?

File: src/tty/unix.rs [hunk 18]
```diff
@@ -15,106 +15,76 @@
...
+use crate::tty::{EventedReadWrite, EventedPty, ChildEvent, ChildInfo};
 use crate::term::SizeInfo;
 use crate::display::OnResize;
 use crate::config::{Config, Shell};
 use crate::cli::Options;
 use mio;
 
-use libc::{self, c_int, pid_t, winsize, SIGCHLD, TIOCSCTTY, WNOHANG};
+use libc::{self, c_int, winsize, TIOCSCTTY};
+use nix::{ unistd::pipe, pty::openpty, sys::signal::* };
```
Comment (chrisduerr) [inline src/tty/unix.rs]: Why the glob import here? Elements should probably be imported individually and the extra whitespace should be removed.

File: src/tty/unix.rs [hunk 19]
```diff
@@ -15,106 +15,76 @@
...
-    let mut status: c_int = 0;
-    unsafe {
-        let p = libc::waitpid(PID, &mut status, WNOHANG);
-        if p < 0 {
-            die!("Waiting for pid {} failed: {}\n", PID, errno());
-        }
-
-        if PID == p {
-            SHOULD_EXIT = true;
+/// We write and signals into the pipe, and the event loop wakes up and reads them.
```
Comment (chrisduerr) [inline src/tty/unix.rs]: Either there's something missing here or the `and` should be removed.

File: src/tty/unix.rs [hunk 20]
```diff
@@ -15,106 +15,76 @@
...
+static mut SIG_PIPE_WRITE: Option<File> = None;
+
+extern "C" fn on_signal(sig: c_int) {
+    let old_errno = errno();
+
+    let byte = [sig as u8];
+    let file = unsafe { SIG_PIPE_WRITE.as_mut().unwrap() };
```
Comment (chrisduerr) [inline src/tty/unix.rs]: While this is perfectly safe, I'm not sure if we want to take any chances here. It's an `Option` already anyways and we just unwrap that, but we could just make it something thread-safe and then return in case there's anything wrong.

An `Option<Arc<Mutex<File>>>` or something similar could just be checked without any potential for error at all, that would probably be a nice change.

File: src/tty/unix.rs [hunk 21]
```diff
@@ -277,12 +253,14 @@ pub fn new<T: ToWinsize>(
...
-            libc::signal(libc::SIGTERM, libc::SIG_DFL);
-            libc::signal(libc::SIGALRM, libc::SIG_DFL);
+            let dfl = SigAction::new(SigHandler::SigDfl, SaFlags::empty(), SigSet::empty());
+            sigaction(Signal::SIGCHLD, &dfl).unwrap();
+            sigaction(Signal::SIGHUP,  &dfl).unwrap();
+            sigaction(Signal::SIGINT,  &dfl).unwrap();
+            sigaction(Signal::SIGQUIT, &dfl).unwrap();
+            sigaction(Signal::SIGTERM, &dfl).unwrap();
+            sigaction(Signal::SIGALRM, &dfl).unwrap();
+            sigaction(Signal::SIGPIPE, &dfl).unwrap();
```
Comment (chrisduerr) [inline src/tty/unix.rs]: Just for documentation, the `sigaction` call will fail when either the signal is invalid or a signal that can't be caught, or the `SaFlags` contain `SA_SIGINFO`. Since the flags are empty and the signals are constant, it is safe to unwrap here and guaranteed to work (assuming it was tested at least once and none of the signals were illegal).

File: src/tty/unix.rs [hunk 22]
```diff
@@ -378,6 +400,40 @@ impl EventedReadWrite for Pty {
...
+    }
+
+    #[inline]
+    fn child_event_token(&self) -> mio::Token {
+        self.sig_token
+    }
+}
+
+pub fn process_should_exit() -> bool {
+    false // TODO: remove this stub if/when windows no longer needs it
```
Comment (chrisduerr) [inline src/tty/unix.rs]: By this I'd assume you mean that we should implement the `get_child_event` method on the winpty and return a new child event when the PTY should quit on Windows?

If this is the case and you don't want to include it in this PR (which is perfectly fine by me, since that's kinda separate anyways), I'd propose opening an issue and removing this TODO, so it's tracked in github. Alternatively the TODO could also document what actually needs to be done and maybe put a link to the issue.

**Comment by rkanati** [comment]
I skimmed these quickly, but I should have time to go through properly this
evening. Thanks!

File: src/event_loop.rs [hunk 23]
```diff
@@ -371,41 +370,51 @@ impl<T> EventLoop<T>
...
+                        CHANNEL_TOKEN => if !self.channel_event(CHANNEL_TOKEN, &mut state) {
                             break 'event_loop;
                         },
+
+                        #[cfg(unix)]
+                        token if token == self.pty.child_event_token() => {
+                            while let Some(child_event) = self.pty.get_child_event() {
+                                if child_event == tty::ChildEvent::Exited {
+                                    let mut term = self.terminal.lock();
+                                    term.exit();
```
[the remark this answers is not in the document]
Comment (rkanati) [reply src/event_loop.rs]: Done.

File: src/tty/mod.rs (hunk 17 above)
Comment (rkanati) [reply src/tty/mod.rs]: Agreed - done.

File: src/tty/unix.rs (hunk 20 above)
Comment (rkanati) [reply src/tty/unix.rs]: I'm not confident putting `Arc` or `Mutex` in there without first being certain they don't do anything that's not async-signal-safe. `Arc`, I assume, can `drop` and thus `free`? Not okay for signal handlers.

Honestly, even using `File` makes me slightly uncomfortable. I'm thinking about using a `RawFd` in an atomic and a `libc::write` instead.

Comment (chrisduerr) [reply src/tty/unix.rs]: `Arc` or `Mutex` don't inherently do anything async unsafe. Quite the opposite they're used to *synchronize* access to a variable.

Now if the variable itself can't be accessed from multiple threads, that's a different thing. But then it shouldn't be publicly accessible at any time anyways. `Arc` or `Mutex` don't make this any worse, they just don't make it any better either.

Using a `RawFd` isn't necessarily any better either. And a `RawFd` can be wrapped in synchronization structs too.

The goal here is to make it impossible to do anything unsafe with it, so adding synchronization across threads is not going to make things worse.

File: src/event_loop.rs [hunk 24]
```diff
@@ -371,41 +370,51 @@ impl<T> EventLoop<T>
...
                     match event.token() {
-                        CHANNEL => if !self.channel_event(&mut state) {
+                        CHANNEL_TOKEN => if !self.channel_event(CHANNEL_TOKEN, &mut state) {
                             break 'event_loop;
                         },
+
+                        #[cfg(unix)]
+                        token if token == self.pty.child_event_token() => {
+                            while let Some(child_event) = self.pty.get_child_event() {
+                                if child_event == tty::ChildEvent::Exited {
```
[the remark this answers is not in the document]
Comment (rkanati) [reply src/event_loop.rs]: That works if `Exited` is the only possible event, and currently it is, but I thought it couldn't hurt to be suggestive here.

File: src/tty/unix.rs (hunk 20 above)
Comment (rkanati) [reply src/tty/unix.rs]: Apologies if I'm misreading you, but I think you may have misunderstood the issue here. Signal handlers aren't merely concurrent like threads, they also operate in a really strange, restrictive context, which makes various seemingly-innocuous operations suddenly really unsafe.

So far, `SIG_PIPE_WRITE` has been okay because it's set once _before_ the handler is installed, and then remains constant... but technically even then we're not 100% correct, because

1. We don't enforce any ordering between setting `SIG_PIPE_WRITE` and installing the handler, and
2. The access in `on_signal` isn't volatile.

There may be better solution to this, however; let me get back to you.

File: src/event_loop.rs (hunk 24 above)
[the remark this answers is not in the document]
Comment (chrisduerr) [reply src/event_loop.rs]: We shouldn't style code for ways things might potentially be in the future.

If there are more events in the future, this can be refactored. Until then a cleaner solution should be preferred.

File: src/tty/unix.rs (hunk 20 above)
Comment (chrisduerr) [reply src/tty/unix.rs]: > Signal handlers aren't merely concurrent like threads, they also operate in a really strange, restrictive context, which makes various seemingly-innocuous operations suddenly really unsafe.

I'm aware of this, however I wanted to point out that the current solution is also vulnerable to those issues. If we want to make things Rust-safe, using Arc and Mutex is an option in the global scope, but obviously an approach should be taken that is not only thread-safe, but also signal-safe.

Of course sometimes there's no way around adding an `unsafe` somewhere, however that should be carefully considered for potential abuse.

File: src/event.rs (hunk 1 above)
Comment (rkanati) [reply src/event.rs]: Okay, I replaced it with an `AtomicIsize` and a `pub fn`, and stripped out the extra plumbing.

Originally I did this thinking it'd be easier to deal with for multiple windows (if we ever do that), but that's probably premature.

**Comment by rkanati** [comment]
Implemented most of your suggestions, @chrisduerr, but I've got one final big trick up my sleeve that might sidestep a lot of it - stay tuned.

**Comment by rkanati** [comment]
...So here's v2.

It's amazing what you can find on crates.io.

**Comment by chrisduerr** [comment]
> It's amazing what you can find on crates.io.

I didn't even think about using a crate for this, but it makes a lot of sense that this is something commonly used and should have a well maintained crate.

File: src/tty/mod.rs [hunk 25]
```diff
@@ -53,6 +53,29 @@ pub trait EventedReadWrite {
...
+/// In particular, this allows for race-free child exit notification on UNIX (cf. `SIGCHLD`).
+pub trait EventedPty : EventedReadWrite {
+    #[cfg(unix)]
+    fn child_event_token(&self) -> mio::Token;
+
+    /// Tries to retrieve an event
+    ///
+    /// Returns `Some(event)` on success, or `None` if there are no events to retrieve.
+    #[cfg(unix)]
+    fn next_child_event(&mut self) -> Option<ChildEvent>;
```
Comment (chrisduerr) [inline src/tty/mod.rs]: We already have a `next_child_event` method, so that would likely raise the question why `EventedPty` doesn't just have a `next` function which returns an `Option<ChildEvent>` using the Iterator trait. And I think that might actually be the correct thing to do here, since a `next_*` method which acts pretty much exactly like an iterator but isn't implemented as an iterator is a bit odd idiomatically.

Just changing this to `pub trait EventedPty: EventedReadWrite + Iterator<Item = ChildEvent>` should take care of the `next` method automatically. The obvious drawback here would be that this is more difficult to do cleanly with the platform-specific annotations, but I don't think that's a huge deal.

**Comment by rkanati** [comment]
I think that's fair that `next_child_event` isn't idiomatic, but an
`Iterator for EventedPty` setup seems a bit... clever.

How about we meet halfway?

```rust
fn child_events(&mut self) -> SomeKindaIterator<ChildEvent>;
```

**Comment by chrisduerr** [comment]
> an `Iterator for EventedPty` setup seems a bit... clever

Hmm it definitely might be a bit clever and usually simple and stupid solutions are the way to go, however I'm not sure if it's too bad in this case.

Having a `child_events` function that returns an iterator seems a bit pointless, since we don't really gain anything here but just make it harder to access the child events since we now need two methods to access events.

Looking at the actual implementation of it on unix, it actually is very close to an iterator though, since we are actually calling the `next()` method on the `pending()` call there. So I feel like an iterator would be the idomatic and clean way to represent what's actually going on, even though we might not need anything beyond the usual `next()` method.

**Comment by rkanati** [comment]
I'm mostly just saying that the call site will look like
```rust
for child_event in pty {
    ...
```
which reads strangely to me... but I'm not gonna die on this hill or anything. I'll go ahead and change it.

**Comment by chrisduerr** [comment]
@rkanati You can just call `next` manually, in which case the callsite should look exactly the same way it does now. Or am I missing something here?

**Comment by rkanati** [comment]
@chrisduerr It just feels less explicit to me. The `pty.child_events()` seems clearer.

**Comment by chrisduerr** [comment]
> It just feels less explicit to me.

That's a great point, since this is a trait the name of the implementing struct doesn't necessarily make it clear what this iterates over.

Since we'll never need any advanced iterator functions, I think keeping it the way it is right now is probably a good idea. Straight-forward and simple too. Thanks for the input!

**Comment by rkanati** [comment]
I'll have a look at the changelog, then.

Also, do you want these commits left as-is (they're fairly neat, I think), or all squashed into one?

**Comment by chrisduerr** [comment]
> Also, do you want these commits left as-is (they're fairly neat, I think), or all squashed into one?

Please do not squash commits. That just makes things tougher to review.

I'll squash them myself before merging, thanks!

**Comment by rkanati** [comment]
There we go.

File: src/term/mod.rs [hunk 26]
```diff
@@ -1336,7 +1336,7 @@ impl Term {
 
     #[inline]
     pub fn should_exit(&self) -> bool {
-        tty::process_should_exit() || self.should_exit
+        self.should_exit
```
Comment (chrisduerr) [inline src/term/mod.rs]: The `use crate::tty;` import should be removed.

File: src/tty/unix.rs [hunk 27]
```diff
@@ -15,54 +15,33 @@
...
-        if p < 0 {
-            die!("Waiting for pid {} failed: {}\n", PID, errno());
-        }
-
-        if PID == p {
-            SHOULD_EXIT = true;
-        }
-    }
-}
+static PID: AtomicIsize = ATOMIC_ISIZE_INIT;
```
Comment (chrisduerr) [inline src/tty/unix.rs]: This has been deprecated and should be replaced with `AtomicIsize::new(0)`, it's also questionable if an isize should be used here at all, since I don't think PIDs can ever be negative.

Comment (rkanati) [reply src/tty/unix.rs]: Huh, weird. I only chose `Isize` since `pid_t` is `i32`, but `Usize` works too.

File: src/term/mod.rs (hunk 26 above)
Comment (rkanati) [reply src/term/mod.rs]: It's actually needed for `tty::isconpty` on windows - I'll pop a `#[cfg(windows)]` on there.

File: src/tty/unix.rs (hunk 27 above)
Comment (chrisduerr) [reply src/tty/unix.rs]: I believe that group IDs can be negative, but I don't think PIDs can be. So using a usize here should be fine.

File: src/term/mod.rs (hunk 26 above)
Comment (chrisduerr) [reply src/term/mod.rs]: Thanks, it's mainly about the compile-time warning. Including it conditionally makes sense here.

**Comment by chrisduerr** [comment]
I think this should be good to go now. I've tested everything and it's looking good. No code issues are jumping out either and the approach seems sane.

Thanks a ton for your work @rkanati, I'm glad this issue is finally resolved.

**Comment by jwilm** [comment]
Thanks for tackling this very long standing issue @rkanati and thanks @chrisduerr for helping to land it! Exciting to finally have this fixed.

**Comment by rkanati** [comment]
Happy to help. I've been on a roll with Rust recently, and this seemed like a good excuse to cut my teeth. Thanks for the learning experience!
