### PR TITLE
Glutin 0.18 upgrade

### LINKED ISSUE #71: Update DPI/DPR when switching monitors
The window size stays the same (post scaling), but the rendered contents stay at the same DPI. When going from low-DPI monitor to a higher-DPI one, this results in the contents not filling the window, and rendering artifacts in the remaining space. Upon resize it adjusts itself to fill correctly. Doing the reverse (high-DPI to lower) results in the contents getting cut off.

Also, because the DPI stays exactly the same, dragging the window from a non-retina monitor to a retina one, the text becomes unreadably tiny instead of scaling up like other windows do.

### LINKED ISSUE #210: Allow alacritty to run on the integrated graphics card on macOS
As it is now, alacritty triggers a switch to the discrete graphics card on dual-graphics macbook pro's. It feels like a bit of overkill to run down the laptop battery by using the discrete card just to run a terminal. 

Apple's official doc for running openGL contexts on the integrated card is at https://developer.apple.com/library/content/qa/qa1734/_index.html , no idea how it relates to rust, though.

### LINKED ISSUE #952: dimensions aren't working
**Which operating system does the issue occur on?**
Debian/sid

**If on linux, are you using X11 or Wayland?**
X11, 5760x2160, 160 dpi

alacritty_hires_size

So you see the dimensions given have nothing in common with the dimensions displayed: 80x25 became something like 48x15 or so. Granted, the DPI is not usual, and ther is custom font, still the resolution seems to be based on the system font used in the title rather than the terminal space.

### LINKED ISSUE #964: Handle winit's DPI Change event
_winit_ added `WindowEvent::HiDPIFactorChanged(f32)`, but none of the backends emit it, yet. Alacritty will need to recompute font size based on the new DPI and flush the glyph cache when the new event is delivered.

This is currently blocked on the event being supported on macOS and X11 _winit_ backends.

cc #510

### LINKED ISSUE #1146: Scaling issues
> Which operating system does the issue occur on?
Fedora 27

If on linux, are you using X11 or Wayland?
> Wayland

screenshot from 2018-03-08 12-52-33

I have tried to look for the configuration on .allacrity.yml but could not find the correct configuration. Tried to increase the font size as well, but doesn't work. Did I miss something?

### LINKED ISSUE #1257: No key repetition on sway 1.0-alpha.1 (Wayland)
Which operating system does the issue occur on?
`Gentoo Linux`

If  on linux, are you using X11 or Wayland?
`Wayland`

---

Hey there, I'm testing out sway's `1.0-alpha.1` release (first release based on wlroots) and it works quite well. Alacritty does start now too (its Wayland backend didn't work with sway `0.15`). That being said, key repetition (holding down a key and repeating the key stroke) doesn't work which makes it barely usable without going mad (navigating files in `vim` is especially painful).

I'm not sure what information should be provided to dig into this issue. Running `alacritty --print-events` gives me these events when pressing and releasing the key `x`:

```
glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(139853503294496))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 45, state: Pressed, virtual_keycode: Some(X), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(139853503294496))), event: ReceivedCharacter('x') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(139853503294496))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 45, state: Released, virtual_keycode: Some(X), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

To me it looks like glutin correctly recognizes key pressing and releasing. Is this an issue with glutin or Alacritty?

### LINKED ISSUE #1345: Decoration free windows can't be resized after glutin 0.16
Which operating system does the issue occur on?
MacOS 10.12.6 (16G1314)

After updating building and launching the release build after the glutin update I am unable to resize the window either through conventional edge grabbing nor through window management tools.

Reverting to the build immediately prior to the glutin update resolved the problem.

I understand this might be a regression in an upstream library.

### LINKED ISSUE #1358: regression: <C-Tab> keybinding no longer works
Which operating system does the issue occur on? macos 10.10.5

If on linux, are you using X11 or Wayland? n/a

the specific keybinding is:

```yaml
  - { key: Tab,      mods: Control, chars: "\x01n",                      }
```

`git bisect` points at [this commit](https://github.com/jwilm/alacritty/commit/765949f256aefcc513d0bfb46b64d315f9c2f3d2), which is just an upgrade of glutin/winit.

I haven't really figured out whether it's an issue with an upstream breaking change or what. Running `winit`'s `window` example, I can see the event come through on the keypress:

```
WindowEvent { window_id: WindowId(Id(140330957578608)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Released, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
```

A `println` [here](https://github.com/jwilm/alacritty/blob/master/src/event.rs#L294) also does show the event coming through, so maybe it has something to do with config parsing or something. I'm going to continue investigating, but wanted to make an issue in case anyone has ideas.

### LINKED ISSUE #1382: Inconsistent window size on HiDPI screen + incorrect font scaling on dpi switch
Which operating system does the issue occur on?

OsX, on a retina display with an attached (non-retina) secondary monitor

I am on the master branch, commit: f55252ec8537e68d0c98a1fac35728a2b596d328

Using the (default) configuration options:

```
window:
  dimensions:
    columns: 80
    lines: 24

scale_with_dpi: true
```

The default alacrity window is much smaller than it should be. Here's a screenshot comparing an 80x24 Terminal.app with an 80x24 alacrity window

screen shot 2018-06-18 at 10 19 14

The screenshot has been obtained running alacrity with the -v flag, so that the window on the left (Terminal.app) contains also the log.

The device pixel ratio seems to be detected correctly (2x on retina displays). I cannot really make full sense of the first "width: ..., height: ..." line (is the size of glyph cache?), but the third (562x338) seems to be just the second (1124x676), scaled down according to the pixel ratio.

My first thought was that the window size was computed prior to the dpi scaling. If that was the case, I would expect that doubling the windows size (in terms of lines and columns) should get a correctly sized window. In practice, doubling up the size...

```
window:
  dimensions:
    columns: 160
    lines: 48
```

...gets very close to Terminal.app 80x24. There is still a slight difference (no need for a screenshot here), but I figure that could be due to minor differences in cell size between the two emulators.

Now, moving the alacrity window on a secondary (non-retina) monitor keeps its size (correctly), but results in double-sized fonts. Here is a screenshot of the two windows, once they have been moved to the secondary monitor.

screen shot 2018-06-18 at 10 42 51

The log (on the left-side window) shows that moving alacrity to the secondary monitor triggered a size update.
```
width: 281, height: 169
```

Just for the record, repeating the process backwards (run on the secondary -- non retina -- monitor, move to the primary -- retina -- monitor) yields reverse results. Here's what happens when first running alacrity (the window has the correct size):

screen shot 2018-06-18 at 10 49 09

And here is what happens when moving both windows on the retina display (window size is kept, half size fonts):

screen shot 2018-06-18 at 10 51 49

Again, the move triggered a size update.

In summary:

- When the window is created, the font size si always correct, but the window size is halved on retina displays
- When the switching to a different monitor, the window size is correctly handled, but the font size is either doubled or halved.

Even  if it looks like to issues, I suspect they are both related to the code for handling the same event. Unfortunately I am not familiar with rust, so I am not sure I would be able to provide more information by looking at the code.

Michele

BTW: guys & gals, many thanks for all your great work!

### LINKED ISSUE #1414: High cpu usage and improper window display and positioning
Operating System - Linux, Wayland, Gnome 3.28.2

-- intro --
Hello I recently tried out alacritty on my desktop for the first time and installed the binary through cargo using rust stable 1.27 

-- problem one -- 
When launched, the alacritty window appears in the top left corner beyond the screen (unable to access titlebar to move the window) and the gnome activities area doesn't allow me to select it and displays it in the wrong position
screenshot from 2018-07-04 23-11-59
screenshot from 2018-07-04 23-11-25
 
-- problem two --
Alacritty appears to use 25% of the cpu, probably because the cpu usage is limited to one core
screenshot from 2018-07-04 23-12-32

### LINKED ISSUE #1428: macOS no longer able to bind Command + Period
I'm on macOS. I just grabbed the latest code (7433f45ff9c6efeb48e223e90dd4aa9ee135b5e8) and built a fresh app via `make app`.

A previous keybinding of mine has stopped working. I had mapped `Command + Period` to send `\x03` as suggested by jwilm via freenode to match the default behavior of macOS's built-in Terminal app. With this latest code base the binding no longer works.

The character sequence in question works great when bound to any other key combination. I am unable to get `Command + Period` to bind to anything, be it my desired character sequence or any other characters or action.

```yaml
# used to work but no longer does
  - { key: Period,   mods: Command, chars: "\x03"                        }

# works fine (Alt instead of Command)
  - { key: Period,   mods: Alt,     chars: "\x03"                        }

# does not work - can't bind Command + Period to anything?
  - { key: Period,   mods: Command, action: IncreaseFontSize             }
```

### LINKED ISSUE #1509: I3 incosistent dpr
Which operating system does the issue occur on?
Linux, WM: I3

If on linux, are you using X11 or Wayland?
X11

I can't reproduce it with the #1403 glutin upgrade. I thought I might report it anyway for future reference.

Sometimes when I launch alacritty I get a DPR of 1 and sometimes 1.666. It happens both if I launch it from dmenu and if I launch it from another terminal. It only happens on my external screen. I tried but can't reproduce it on the laptop screen. I'm not sure what the correct DPR should be..

# External screen

* 1920x1200
* 24"

```
$ alacritty -vvv
Welcome to Alacritty.
Configuration loaded from /home/niklas/.config/alacritty.yml
device_pixel_ratio: 1.6666666
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.074482644
width: 884, height: 508
Cell Size: (11 x 21)
PTY Dimensions: Line(24) x Column(80)
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Deriving dim colors from normal colors
Scaling RGB by 0.66 from Rgb { r: 0, g: 43, b: 54 } to Rgb { r: 0, g: 28, b: 35 }
Scaling RGB by 0.66 from Rgb { r: 220, g: 50, b: 47 } to Rgb { r: 145, g: 33, b: 31 }
Scaling RGB by 0.66 from Rgb { r: 133, g: 153, b: 0 } to Rgb { r: 87, g: 100, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 181, g: 137, b: 0 } to Rgb { r: 119, g: 90, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 38, g: 139, b: 210 } to Rgb { r: 25, g: 91, b: 138 }
Scaling RGB by 0.66 from Rgb { r: 108, g: 113, b: 196 } to Rgb { r: 71, g: 74, b: 129 }
Scaling RGB by 0.66 from Rgb { r: 42, g: 161, b: 152 } to Rgb { r: 27, g: 106, b: 100 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Deriving dim colors from normal colors
Scaling RGB by 0.66 from Rgb { r: 0, g: 43, b: 54 } to Rgb { r: 0, g: 28, b: 35 }
Scaling RGB by 0.66 from Rgb { r: 220, g: 50, b: 47 } to Rgb { r: 145, g: 33, b: 31 }
Scaling RGB by 0.66 from Rgb { r: 133, g: 153, b: 0 } to Rgb { r: 87, g: 100, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 181, g: 137, b: 0 } to Rgb { r: 119, g: 90, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 38, g: 139, b: 210 } to Rgb { r: 25, g: 91, b: 138 }
Scaling RGB by 0.66 from Rgb { r: 108, g: 113, b: 196 } to Rgb { r: 71, g: 74, b: 129 }
Scaling RGB by 0.66 from Rgb { r: 42, g: 161, b: 152 } to Rgb { r: 27, g: 106, b: 100 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Font size changed: Size(16)
Term::resize
num_cols, num_lines = 86, 55
width: 956, height: 1161
Set Attribute: Bold
Set Attribute: Foreground(Named(Red))
Set Attribute: Bold
Set Attribute: Foreground(Named(Blue))
Set Attribute: Bold
Set Attribute: Foreground(Named(Magenta))
Set Attribute: Reset
Set Attribute: Bold
Set Attribute: Foreground(Named(Blue))
Set Attribute: Reset
carriage_return
carriage_return
linefeed
carriage_return
linefeed
Goodbye.
niklas @ niklas-tp : ~
$ alacritty -vvv
Welcome to Alacritty.
Configuration loaded from /home/niklas/.config/alacritty.yml
device_pixel_ratio: 1
width: 956, height: 1161
Initializing glyph cache
Finished initializing glyph cache in 0.071736613
width: 484, height: 292
Cell Size: (6 x 12)
PTY Dimensions: Line(24) x Column(80)
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Deriving dim colors from normal colors
Scaling RGB by 0.66 from Rgb { r: 0, g: 43, b: 54 } to Rgb { r: 0, g: 28, b: 35 }
Scaling RGB by 0.66 from Rgb { r: 220, g: 50, b: 47 } to Rgb { r: 145, g: 33, b: 31 }
Scaling RGB by 0.66 from Rgb { r: 133, g: 153, b: 0 } to Rgb { r: 87, g: 100, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 181, g: 137, b: 0 } to Rgb { r: 119, g: 90, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 38, g: 139, b: 210 } to Rgb { r: 25, g: 91, b: 138 }
Scaling RGB by 0.66 from Rgb { r: 108, g: 113, b: 196 } to Rgb { r: 71, g: 74, b: 129 }
Scaling RGB by 0.66 from Rgb { r: 42, g: 161, b: 152 } to Rgb { r: 27, g: 106, b: 100 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Deriving dim colors from normal colors
Scaling RGB by 0.66 from Rgb { r: 0, g: 43, b: 54 } to Rgb { r: 0, g: 28, b: 35 }
Scaling RGB by 0.66 from Rgb { r: 220, g: 50, b: 47 } to Rgb { r: 145, g: 33, b: 31 }
Scaling RGB by 0.66 from Rgb { r: 133, g: 153, b: 0 } to Rgb { r: 87, g: 100, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 181, g: 137, b: 0 } to Rgb { r: 119, g: 90, b: 0 }
Scaling RGB by 0.66 from Rgb { r: 38, g: 139, b: 210 } to Rgb { r: 25, g: 91, b: 138 }
Scaling RGB by 0.66 from Rgb { r: 108, g: 113, b: 196 } to Rgb { r: 71, g: 74, b: 129 }
Scaling RGB by 0.66 from Rgb { r: 42, g: 161, b: 152 } to Rgb { r: 27, g: 106, b: 100 }
Scaling RGB by 0.66 from Rgb { r: 147, g: 161, b: 161 } to Rgb { r: 97, g: 106, b: 106 }
Font size changed: Size(16)
Term::resize
num_cols, num_lines = 158, 96
width: 956, height: 1161
Set Attribute: Bold
Set Attribute: Foreground(Named(Red))
Set Attribute: Bold
Set Attribute: Foreground(Named(Blue))
Set Attribute: Bold
Set Attribute: Foreground(Named(Magenta))
Set Attribute: Reset
Set Attribute: Bold
Set Attribute: Foreground(Named(Blue))
```

# Laptop screen

* 1920x1080
* 14"

```
niklas @ niklas-tp : ~
$ alacritty -vv
Welcome to Alacritty.
Configuration loaded from /home/niklas/.config/alacritty.
device_pixel_ratio: 1.6666666
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.05609836
width: 884, height: 508
Cell Size: (11 x 21)
PTY Dimensions: Line(24) x Column(80)
Font size changed: Size(16)
Term::resize
num_cols, num_lines = 57, 49
width: 636, height: 1041
```

### LINKED ISSUE #1525: F16-F19 keys not working properly.
Which operating system does the issue occur on? macOs 10.14 public beta 7

My config for F keys:
screenshot 2018-08-27 at 19 58 32

Screen cast in alacritty ( I'm pressing keys from F13 to F19)
TERM: xterm-256color

ezgif-2-846e274177

Screen cast in iterm2 ( I'm pressing keys from F13 to F19)
TERM: xterm-256color

ezgif-2-bd5af78a1b

### LINKED ISSUE #1756: Unknown character in window title
Since the last update I have an unknown symbol in my title bar.
screenshot-2018-11-07-15 07 09
This also happens if I set the window_title to non-dynamic.
I am using Arch Linux and i3 (so I am on X11) and I don't have this problem with other applications.

### PR DESCRIPTION
**Pull request by mkeeler**
Fixes #1756 
Fixes #1525
Fixes #1509
Fixes #1428
Fixes #1414 
Fixes #1382
Fixes #1358
Fixes #1345 
Fixes #1257 
Fixes #1146
Fixes #964 
Fixes #952
Fixes #210 
Fixes #71 

This compiles and after reviewing looks sane enough. However I am running into an issue where the text output of the terminal only shows up on the lower left quadrant of the whole window.

I figured I could go ahead and open this up as a work in progress to get some feedback and suggestions for what could have gone wrong.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Thanks for sending the PR! Excited to land this huge glutin/winit update!

Hey, the text only showing up in the lower-left quadrant could be related to what I've mentioned in #210 already. Since we rely on actually knowing the real pixel size to calculate the number of columns and lines in the active terminal window.

There's two possible approaches we could take here. Either we calculate the number of columns and lines based on scaled size, then we'd have to transform the reported pixel sizes of glutin to the actual scaled DPI sizes (I'd assume multiplying by DPI factor might work). The other option is to always calculate based on real pixel width/height of the window, in which case we'd need to convert the reported height/width by glutin to unscaled values.

The cell width/height is probably the major issue, however we'll have to do the same thing with the terminal padding too.

I haven't taken any look at the code yet and I'll probably have to wait until tomorrow to do so, but this seems like a good guess.

**Comment by chrisduerr** [comment]
Just to make sure you've got a lead and don't have to poke around inside a codebase you haven't worked with before, here are at least some places you should be looking at:

https://github.com/jwilm/alacritty/blob/master/src/display.rs#L164-L176
Here we set the width/height based on the column/lines specified in the config. You can probably ignore this at first until you've got things working by default, but it's likely this will also need some fixes.

https://github.com/jwilm/alacritty/blob/master/src/display.rs#L180-L187
This is the place where the original dimensions are calculated, the columns and lines are methods on the `SizeInfo` struct (see code in src/term/mod.rs for the implementation). At least with my WM the window is resized immediately after being created though, so you probably won't see any changes when altering the code here unless that's different for your WM.

https://github.com/jwilm/alacritty/blob/master/src/display.rs#L307-L320
This is where the actual resize is handled, I was able to get some immediate results by playing with DPR here. If your WM resizes directly at startup (you should be able to see something like `num_cols, num_lines = 240, 61` in the `alacritty -v` output), this is probably the place you should investigate first, because everything else is not going to show any results.
To do anything with DPI in the `handle_resize` method, you can look at #1362 which should already have all the necessary code for this. Just rebasing on top of that PR might make some sense here. I might also be able to merge this PR, since it is fairly straight-forward.

These are all the guidelines I could think of at this moment, hopefully that will help you out a bit in case you didn't know where exactly to look to make these changes. As always if you have any questions, feel free to ask on github/irc! :)

**Comment by mkeeler** [comment]
@chrisduerr I finally got it working.

It turns out there was an issue when handling the resized event emitted by glutin. In glutin 0.16 the Resized event was emitted already scaled with the hidpi_factor to be a physical/point size but in this version of glutin a Logical/pixel size is emitted.

Unfortunately that wasn't in the list of winit breaking changes in their CHANGELOG.md.

Either way this now is working as expected for me.

One last note is that I had attempted to change the SizeInfo struct to storing either a winit PhysicalSize or LogicalSize and in general making those types more pervasive throughout the code base (instead of u32s everywhere else). However due to not implementing various traits I could not use those types there. That may be something to figure out in the future.

**Comment by mkeeler** [comment]
So I just looked at discrete GPU usage again with alacritty and its not working again even with the glutin update.

Prior to all the hidpi/winit changes it was working perfectly fine with alacritty built with glutin 0.16 + my glutin PR to fix the GPU switching issue. Something is up and it will require more investigation to figure out exactly what.

**Comment by mkeeler** [comment]
One thing to note is that for the GPU switching to work it requires the full .app version. If you run the binary direct MacOS will force it into using the discrete GPU.

**Comment by francesca64** [comment]
> Unfortunately that wasn't in the list of winit breaking changes in their CHANGELOG.md.

From the CHANGELOG:

> - **Breaking:** The entire API for sizes, positions, etc. has changed. In the majority of cases, winit produces and consumes positions and sizes as `LogicalPosition` and `LogicalSize`, respectively. The notable exception is `MonitorId` methods, which deal in `PhysicalPosition` and `PhysicalSize`. See the documentation for specifics and explanations of the types. Additionally, winit automatically conserves logical size when the DPI factor changes.

**Comment by chrisduerr** [comment]
I have to say I'm actually a big fan of winit/glutin's CHANGELOG. I think it would be awesome for Alacritty to introduce something similar, this should make it easier for people to see what kind of changes the can expect or where breakage might be coming from!

**Comment by mkeeler** [comment]
@francesca64 I went into it knowing that all the sizing things had changed. I interpreted the change log as thinking that all the types were different but underlying functionality was mostly unaltered. I guess that’s just me misunderstanding the changelog.

**Comment by chrisduerr** [comment]
I'd love for this PR to get some more testing before merging it into master. I can imagine that due to the many sizing changes it's a possibility that things like resizing/selection and similar could have changed.

So if anyone wants to help out and chime in, it would be much appreciated!

**Comment by chrisduerr** [comment]
@mkeeler Based on the testing I've done, it looks like the window size does not adjust based on DPI when the window changes screen. Can you confirm this to be the case?

Even though the font size itself doesn't updated yet (see #1362 and #1346 for more info on this), it might make sense to introduce that change with this PR.

I'd be fine with mirroring the behavior of the current master, where the window stays the same size when changing screen. However long-term it will definitely be desired to change this and make use of the DPI information for window size too.

**Comment by mkeeler** [comment]
@chrisduerr I haven’t tried with switching displays and I won’t have access to my external display until next Monday. 

I might be able to simulate it with changing the dpi scaling on the internal display on my laptop. 

One thing that I did test outside of just resizing things and basic window operations was manually changing font sizes and watching alacritty properly recalculate the new number of lines and columns. 

I will review those other two prs to get some context and then get back with you.

**Comment by francesca64** [comment]
>  it looks like the window size does not adjust based on DPI when the window changes screen

winit does that automatically? Or are you talking about in terms of cells?

**Comment by chrisduerr** [comment]
@francesca64 I'm talking about the size of the window. Based on what I've understood from your previous comments about this change, I'd expect the physical size of the window to be the same when changing screens with this PR. However this is not the case.

Since DPI does not scale automatically the window size should change and the number of column available should change. However the number of lines and columns stays the same at least on my machine (x11/i3). We might explicitly request this, I haven't looked at the actual code of the PR yet.

**Comment by francesca64** [comment]
The logical size is conserved when the DPI changes, not the physical size.

**Comment by chrisduerr** [comment]
@francesca64 I might be misunderstanding something here. Isn't the logical size the size of the window scaled by DPI? Which would in return mean that the physical size (on the monitor) is the same?

Opposed to the pixel size which is the same on each monitor, but not scaled by DPI, so it will lead to different physical sizes?

Or are we talking about something completely different here?

**Comment by francesca64** [comment]
Have you read the docs? https://docs.rs/winit/0.16.1/winit/dpi/index.html

**Comment by chrisduerr** [comment]
According to docs:
```
Ideally, the button now has approximately the same perceived size across varying displays.
```

Which is (as far as I understand it) exactly what I've been saying. The perceived size (ruler to the screen) of the window should be the same on all monitors. However in this branch it is not.

I'm sorry if I'm misunderstanding something, but this is the way I've been thinking about the DPI stuff this whole time and the docs you've linked seem to support that point of view.

**Comment by francesca64** [comment]
Ah, I see. You meant *physical* physical size, like in mm. I thought you meant in terms of physical pixels... now it makes sense!

**Comment by mkeeler** [comment]
@chrisduerr This PR will cause conflicts with both those other PRs. Do the alacritty devs have a usual procedure for doing this? I could merge those other two branches into mine and fix all the conflicts with the glutin update or would you rather keep the changes in separate PRs?

**Comment by mkeeler** [comment]
So a new issue I just found is that mouse selection seems to only want to use the top 50% of the lines for selection.

**Comment by chrisduerr** [comment]
I don't think you should worry about the other PRs, the one from sodiumjoe is still a WIP which needs some changes and I'm always happy to rebase mine on top of the latest master and fix all existing issues. I think the general rule is that whoever comes first got lucky and everyone else has to adapt. :D

With the selection issue I'd assume that there is some limiting calculation going on somewhere that makes sure the mouse cursor's position is limited to within the window and that might still be in physical pixels, but I'd also have to look into it. If you need any help with figuring this out, please let me know and I can take a closer look myself.

For me it just seems like the selection points are just a lot higher than the actual mouse pointer, there is no clear line for me where selection works normally and where it doesn't.

Also @francesca64 turns out I'm a moron, I probably should have tested the `glutin-0.17-upgrade` branch from mkeeler instead of `master`. I've re-tested it on the correct branch and the window size is changed according to DPI, it doesn't result in a perfect match in cm but I'd assume that's mostly because of minor rounding problems or similar things, either way it's close enough. I've also confused people calling the cm size 'physical' multiple times now, I probably shouldn't be trusted with anything I'm saying at this point, thanks for the guidance though! :)

**Comment by chrisduerr** [comment]
@mkeeler I've fixed the selection issue #[here](https://github.com/chrisduerr/alacritty/tree/glutin-0.17-upgrade), feel free to merge this into your branch or just pick out what you think makes sense.

Unfortunately I can't send a PR to your branch and even though I think I have permission to push directly to your branch, I don't want to force this down on you. :D

If you have any ideas for improvements on top of my changes, feel free to add those.

**Comment by mkeeler** [comment]
Thanks. I had tried a few different things but was starting to go down the route of storing the dpi info in the SizeInfo struct and it looks like that was the correct approach. 

One other thing I tried that didn’t go so well was a larger integration of the winit size types into the SizeInfo struct and a few other places. However I ran into issues with serde serialization and deserialization of those types. Serde for whatever reason couldn’t derive the implementation and as both the traits and types are in other crates the compiler didn’t want to allow me to provide the implementation myself. Eventually it would probably be good to have clear separation of where logical vs physical sizes are used but I don’t see it as a must have for this PR. 

Feel free to push changes too my branch. I am not at all protective of the code. I probably won’t be in front of a computer until Monday to do it myself.

**Comment by mkeeler** [comment]
@chrisduerr At this point I know of no other bugs or changes that need to be made. Just more testing.

I have been using a build from my branch as my main terminal and will continue to do so until this gets merged. If any other issues come up I will post here.

**Comment by chrisduerr** [comment]
Yeah based on my testing everything seems pretty good so far. I'd like to do a more extensive code review before merging though. However I'm not sure if this will be merged before scrollback because it introduces a lot of regression potential.

**Comment by mkeeler** [comment]
@chrisduerr The preferences for dimensions look to be wrong. When I ask for 10 lines I get 20 on macos so it seems like its using the dpi factor and doubling things. I will work on fixing this.

As for the DPI scaling preference, couldn't we 1) remove the current scale_with_dpi preference and 2) add a new dpi_factor preference. When configuring the window we would pass the pref in and the windows hidpi_factor function could return that value if not 0.0 and otherwise ask winit for the windows hidpi_factor. That way we could just call the hidpi_factor function on the window everywhere and have it work as desired.

**Comment by mkeeler** [comment]
My latest commit fixes the dimensions preferences issue.

**Comment by chrisduerr** [comment]
We could definitely make a config option that allows freely setting any DPI, however that's not really the issue. The problem is that winit will still resize the window when moving monitor based on the real DPI, not our set DPI. If we actually want to be able to override DPI, we'd need to either add a functionality to winit to run with custom DPI, or we'd need to undo winit's scaling whenever it happens. So when the window size changes because of DPI change, we'd need to receive the event and pretty much ask the window to be resized again to the old size.

**Comment by mkeeler** [comment]
Looking through the winit code and reading some macos cocoa docs, I don't believe the physical resizing is done by winit (at least not for macos). I think the NSWindow/NSView are going to auto-scale with DPI changes. @francesca64 is this accurate.

So if we want to keep the same physical size when alacritty has dpi scaling off then I think the only thing that can be done is to pick up the HiDpiFactorChanged event and calculate the physical size we desire and resize it ourself.

**Comment by chrisduerr** [comment]
Yeah that's the point I was trying to make. The window will be resized automatically by winit and the dpi change event (and I think also the resize event) will be sent. Once that is done we'd have to undo the automatic resize winit does and use our own dpi again.

**Comment by francesca64** [comment]
X11 and Windows natively use physical pixels, so winit's logical pixel handling is layered on top of that. macOS and Wayland natively use logical pixels, so winit does nothing special there. Adding this functionality within winit would be a matter of adding a layer that does the inverse of that, which I'm not opposed to, but don't have time for. https://github.com/tomaka/winit/issues/591#issuecomment-403113701

**Comment by chrisduerr** [comment]
@francesca64 It's nice to hear that winit isn't opposed to something like this. I might look into sending a PR to winit then which would add the method `with_hidpi_factor(f64)` for the window creation and `window.set_hidpi_factor(f64)` for changing it at runtime. 

I'm not entirely sure yet if winit is the best place for this, or if Alacritty should provide an option that is more than enable/disable at all, so I'll have to look a bit more into this first. But I think that in general providing this option shouldn't be an awful thing assuming that it can be cleanly implemented. Especially on Linux a lot of users seem to be used to have no DPI scaling, so they shouldn't be forced into it either.

**Comment by chrisduerr** [comment]
I've thought about this again and I don't think disabling the DPI is something any platform other than X would be interested in, however for X11 there's still `WINIT_HIDPI_FACTOR=1.0` to disable DPI scaling.

So I think we should actually be fine with just removing that setting, assuming that `WINIT_HIDPI_FACTOR=1.0 alacritty` works properly.

**Comment by chrisduerr** [comment]
@mkeeler I've just added a new commit which removes the `scale_with_dpi` flag from the config, so we don't have to worry about this anymore.

I've also fixed a bug where text would be rendered incorrectly when moving alacritty between monitors with different DPIs.

This means that this PR effectively replaces #1362 and #1346. This also means issues #964 and #71 are now also resolved through this PR.

**Comment by mkeeler** [comment]
@chrisduerr Thanks for making those changes. One main thing I see is that the HiDpiFactorChanged event doesn't actually set the dpr anywhere.

Assuming my reading of the winit code is correct, it looks like you aren't guaranteed to get a resize event along with each dpi change event. At least one example is in the [wayland backend](https://github.com/tomaka/winit/blob/e7a8efcfa0b0b3b6518fb9f11541cd5a8895965f/src/platform/linux/wayland/event_loop.rs#L248)

With that, shouldn't the dpi event be handled like in #964?

**Comment by chrisduerr** [comment]
@mkeeler The `handle_resize` method is always called when the terminal is dirty (see #[here](https://github.com/jwilm/alacritty/blob/master/src/main.rs#L196)). So it's correct that I'm not doing anything other than setting the terminal to be dirty, but as a result the `handle_resize` method will be called which checks if the dpi changed and assigns the new value to `size_info` and then updates the glyph cache.

However I was not able to test this on X11, but it should be fine.

**Comment by chrisduerr** [comment]
I've also updated the dependencies since there was some update in the smithay-client-toolkit which should greatly improve the behavior and look of winit windows in wayland.

**Comment by petobens** [comment]
@chrisduerr do i need to change something in my alacritty config file to have proper font size when moving between monitors? https://github.com/jwilm/alacritty/pull/1346 seem to work just fine but I'm having trouble with this PR. For the record I'm on Mac and this is my alacritty config: https://github.com/petobens/dotfiles/blob/master/config/alacritty/alacritty.yml

Also: I don't know if it is related or not but when I switch between monitor the cursor is lost.

**Comment by mkeeler** [comment]
@petobens are you switching between hidpi and non-hidpi monitors? When you say you are having trouble what is the behavior you are seeing that is undesirable?

**Comment by petobens** [comment]
@mkeeler thanks for looking into this. I'm indeed switching between a hidpi monitor (my retina display macbook pro screen) and a regular non-hidpi monitor. What I meant by trouble is that the text is not adjusted when switching between monitors (it is either too huge or too small in one them and I have to adjust it manually). This wasn't the case with #1346 .

**Comment by mkeeler** [comment]
@chrisduerr I dont think its related to the font issue but shouldn't this line: https://github.com/mkeeler/alacritty/blob/6a6520a3be0998b3783c5fb26bdc3f2bf0b44e3f/src/display.rs#L295 get moved to before we pull the resized event from the queue on line 288.

Something like this:

```
        // Update the DPR 
        let dpr = self.window.hidpi_factor();

        // Take most recent resize event, if any
        while let Ok(sz) = self.rx.try_recv() {
            // Resize events are emitted via glutin/winit with logical sizes
            // However the terminal, window and renderer use physical sizes
            // so a conversion must be done here
            new_size = Some(sz.to_physical(dpr));
        }

        // Font size/DPI factor modification detected
        if terminal.font_size != self.font_size || dpr != self.size_info.dpr {
            self.font_size = terminal.font_size;```

That makes it so that the new physical size takes into account any dpr changes.

**Comment by chrisduerr** [comment]
@mkeeler Good point, I think I both refactored `new_size` to use `size_info.dpr` and then moved the actual `dpr` definition to a different place. It looks to me like your correction is accurate.

Would you mind applying these changes and giving it a quick shot? I can test it on my multi-dpi setup too, just to make sure things actually work.

**Comment by mkeeler** [comment]
I have been running with the changes for most of today and things seem normal to me. Although all my screens will have the 2.0 dpr on macos so I didn't really expect to see any difference

**Comment by chrisduerr** [comment]
So I'm thoroughly confused right now. I've tested this change and it broke the text rendering for me when moving windows between outputs (part of the text was offscreen).

So I've reverted the last commit to make sure this was working fine before and it did.

Then I've pulled the latest version again to check which part exactly caused a failure and I couldn't reproduce it anymore.

After a bit of tweaking I found the root cause of this though: I use a tiling WM. If I move a floating window from one screen to another, the size changes and everything's working fine. However if I move the window from one screen to another in tiling mode (which force-resizes it itself), the text will be rendered incorrectly.

I can look closer into fixing this tomorrow, but it seems like there are some issues with resizing when winit/glutin is not in control but the window manager is. I was not able to reproduce this in floating mode.

File: src/display.rs [hunk 1]
```diff
@@ -285,28 +283,37 @@ impl Display {
         // events into one.
         let mut new_size = None;
 
+        // Update the DPR 
+        let dpr = self.window.hidpi_factor();
+
```
Comment (chrisduerr) [inline src/display.rs]: There's a trailing whitespace after the "DPR" comment here and it's probably cleaner to have just one empty line instead of two after `let dpr = ...;`.

**Comment by chrisduerr** [comment]
@petobens This looks good to me. It's correctly detecting the DPI change from one monitor to the next one and will double the size of your font on the hidpi monitor.

**Comment by petobens** [comment]
@chrisduerr can I set from the config file that scale factor (i.e avoid doubling which doesn't look good at all)?
Mmm the `Size(32)` in both cases is correct? Shouldn't one be 16 and the other 32?

**Comment by petobens** [comment]
My more general question is that when using #1346 the font size change when switching monitors seemed to be handled a bit more gracefully. Is there a way to recover that behaviour?

**Comment by chrisduerr** [comment]
The reported size is not scaled by DPI. That is the original font size without any scaling applied.

I'm not sure which commit exactly #1346 is based on, it's possible that it just doesn't do any proper DPI adjustment yet.

Currently Alacritty just always renders at the correct DPI. In you example it sounds like Alacritty is doing things right.

**Comment by mkeeler** [comment]
I think there may be something to this. In update_glyph_cache we attempt to use the dpr to resize the font. Also the logs showing a font size of 32 with a dot of 2 down to a size of 32 with dot of 1 seems odd. I think there is a font scaling issue there.

**Comment by chrisduerr** [comment]
I have a setup with two screens with different DPIs and everything seems to work correctly. When starting out on the 1.66666... screen and moving to the 1.0 one I get the same font sizes as I do when I move from the 1.0 one to the 1.666... screen.

If the DPI would be applied on top of a scaled font size based on the original DPI, the move from the 1.6666666... screen to the 1.0 screen should not change the font size at all. So it seems like everything should be going smoothly.

@petobens The goal of proper DPI scaling is that on both your monitors the application should be the same size in mm. So if you take a ruler to your screen it should be approximately the same no matter which screen it's displayed on. If this is not the case and there are some significant differences which are clearly outside of rounding problems (like one being twice the size of the other), then it might be a bug.

**Comment by petobens** [comment]
Thanks @chrisduerr . I have the following two monitors:
```
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2560 x 1600 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
        23MP55:
          Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
          UI Looks like: 1920 x 1080 @ 60 Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number:
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DVI or HDMI
          Adapter Firmware Version:  c.55
```
This is how it look in the non retina display (23MPP):
screen shot 2018-07-18 at 19 30 47 2


And if I switch to the retina one:
screen shot 2018-07-18 at 19 34 49

Maybe this is expected (but in order to see it/work properly on the retina display I need to zoom in). Sorry not being able to be of any further help.

**Comment by chrisduerr** [comment]
@petobens This doesn't look correct, I'll take another look at the MacOS code.

I'd assume that the size in mm is quite different on the two monitors? With screenshots it can be quite difficult to give a concrete estimation of DPI sometimes. But it looks like things are incorrect here.

**Comment by mkeeler** [comment]
I cant test mm to mm comparisons but I airplayed my screen to a 1080p apple tv and the font size does get ridiculously large when I change screens.

**Comment by chrisduerr** [comment]
@mkeeler This is not actually related to DPI at all. This scale factor is used to make it possible to allow `.5` increments of the font size in the config while still keeping it as whole numbers internally (So 12.5 -> 25).

**Comment by mkeeler** [comment]
I thought it might be something like that but just didn't have the background. At least it explains why the logs show a font size that is 2x the configured font size.

**Comment by petobens** [comment]
Maybe @sodiumjoe can chime in? In #1346 he comments that apparently these changes are working properly for him.

**Comment by chrisduerr** [comment]
@petobens You can find a patch [here](https://paste.rs/Lwx) which will print the actual pixel size whenever you move the window from one monitor to another.

If everything is working correctly, I'd expect that on your 1.0 DPI screen the size should be `X` and on your 2.0 DPI screen the size should be `2 * X`.

If you can't get this patch to work correctly, please report back. I'm unfortunately unable to test on macOS but this should work.

**Comment by petobens** [comment]
I'm getting the following output when applying the patch:
```
Term::resize
num_cols, num_lines = 120, 30
width: 1086, height: 620
REAL SIZE: 32
REAL SIZE: 32
REAL SIZE: 32
REAL SIZE: 32
REAL SIZE: 32
carriage_return
clear_line: Right
Set Attribute: Foreground(Indexed(235))
Set Attribute: Background(Spec(Rgb { r: 97, g: 175, b: 239 }))
Set Attribute: Bold
Set Attribute: Foreground(Spec(Rgb { r: 97, g: 175, b: 239 }))
Set Attribute: Background(Spec(Rgb { r: 208, g: 208, b: 208 }))
Set Attribute: Bold
Set Attribute: Reset
set_cursor_style Some(Beam)
Set Attribute: Reset
Set Attribute: Foreground(Spec(Rgb { r: 36, g: 39, b: 46 }))
Set Attribute: Background(Spec(Rgb { r: 208, g: 208, b: 208 }))
Set Attribute: Bold
Set Attribute: Reset
Set Attribute: Foreground(Spec(Rgb { r: 208, g: 208, b: 208 }))
Set Attribute: Background(Spec(Rgb { r: 40, g: 44, b: 52 }))
Set Attribute: CancelBoldDim
Set Attribute: Reset
Set Attribute: Foreground(Spec(Rgb { r: 130, g: 137, b: 151 }))
Set Attribute: Background(Spec(Rgb { r: 40, g: 44, b: 52 }))
Set Attribute: Bold
Set Attribute: Reset
Set Attribute: Foreground(Spec(Rgb { r: 40, g: 44, b: 52 }))
Set Attribute: Background(Named(Background))
Set Attribute: CancelBoldDim
Set Attribute: Reset
REAL SIZE: 16
Font size changed: Size(32) [DPR: 1]
REAL SIZE: 16
REAL SIZE: 16
REAL SIZE: 16
REAL SIZE: 16
```
So I guess this is indeed working as expected? Can it be something my the font i'm using? For the record it's SauceCodePro Nerd Font.

The other thing I can think about is something messing with the zoom factor? (just guessing here, I believe @sodiumjoe  a way better tester than myself and might be able to shed some light).

Once again thanks for looking into this.

**Comment by chrisduerr** [comment]
@petobens I'm not sure if I can help you at this point. Everything seems to indicate that things are going smoothly.

Having a video/screenshot of your monitors would be tough, but if you really think something's not right, you can record your screens with a camera and share that. This should make it pretty obvious if things are going okay or completely wrong.

Also what's the behavior of the current master branch? It's not possible to move windows between screens yet, but if you open a window on the different screens directly, it should scale properly. So try opening a master branch window on each screen, then spawn a window of this PR on one monitor, make sure the size is the same as the master branch window on that monitor, then move it to the other screen and compare font size again.

**Comment by chroosh** [comment]
Just tried to test this locally, compiled fine, but when I run the program it panics:

> thread 'main' panicked at 'The `scale_with_dpi` field has been deprecated, on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.', src/config.rs:1563:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Had a look through the code as well to find source of the panic (no Rust experience) - is it still WIP? (mentioned a Todo on 1555 in config.rs) Or am I missing something here?

**Comment by OkanEsen** [comment]
You need to remove `scale_with_dpi: true` in your `alacritty.yml` @chroosh.

**Comment by chrisduerr** [comment]
Unfortunetly screen recordings aren't of much help when it comes to DPI, since it depends on the pixel density (which is not captured by a screen recording).

I trust in your judgement that the behavior of Alacritty is incorrect in this PR at the moment, assuming that the master branch does the right thing. However I do not have any way to test this on macOS, so it's hard for me to fix this. I don't see any obvious errors and it seems to work fine on Linux, so there's not much I can do at this point.

**Comment by mkeeler** [comment]
I am thinking this may be something related to glyph caching. What I just tested.

1. Open alacritty on my mbp internal screen. (font size of 16 things look normal)
2. Move alacritty to external 1080p display. (font size looks huge)
3. cmd + '+' to increase the font size to 16.5 and the font shrinks.
4. cmd + '-' to decrese the font size back to 16 and the font gets huge again.

Still looking into it.

Also @chrisduerr it looks like the font library has a custom impl for darwin so maybe thats why it has seemed okay to you.

**Comment by chrisduerr** [comment]
Yeah when it comes to fonts linux and macOS are definitely very different. I'll gladly help anyone troubleshoot it, but I've had very limited success with macOS VMs especially with multiple monitors, so it's a bit hard to really troubleshoot that kind of stuff for me.

**Comment by mkeeler** [comment]
@chrisduerr is it expected for the cell width and height to change when changing screens? It doesn't for me when going between two displays.

**Comment by chrisduerr** [comment]
With [this](https://paste.rs/mYU.diff) diff, you should notice that when moving the window from one window to a different window, that the cell width/height should change.

So as an example: If I create a window I get cell dimensions of `8x16` on my `1.0` DPI screen, once I move them to my `1.666666666666666....` DPI screen, I will get dimensions of `9x19`. If you multiply `8x16` by `1.666...`, you'll notice that you get exactly `9x19` (with rounding).

So if you have a DPI of `2.0`, the result with this patch applied should show that the cell width/height doubles once moving it to a different screen. If this is not the case, something's borked.

**Comment by mkeeler** [comment]
Okay that definitely isn't happening for me.

Also I tried replacing the update_glyph_cache function with the replace_glyph_cache function from #1346 and then everything works as expected.

**Comment by chroosh** [comment]
Thanks for that @mkeeler, works well! Although, the scrolling appears to be half the speed of what it used to be in vim - not sure if related.

Also now that fonts are the same size across different monitors + since window padding isn't scaled by DPI, the change in pixel padding going from one monitor to another is quite noticeable.

**Comment by mkeeler** [comment]
@chrisduerr I think I figured it out.

In the Rasterize impl for macos there is [load_font](https://github.com/mkeeler/alacritty/blob/glutin-0.17-upgrade/font/src/darwin/mod.rs#L149). This looks up the font in a HashMap using the font descriptor and size. If it exists the previously loaded font key gets returned. Otherwise it calls [get_font]([url](https://github.com/mkeeler/alacritty/blob/glutin-0.17-upgrade/font/src/darwin/mod.rs#L241)).

get_font then either loads the font by calling get_specific_face or get_matching_face. Both of those functions scale the size of the font based on the dpr.

That HashMap always gets accessed with a raw size (unscaled by dpr) but the font it loads is scaled. I tried using with the following patch and then things worked properly.

```
diff --git a/font/src/darwin/mod.rs b/font/src/darwin/mod.rs
index d5d0399..7eb2396 100644
--- a/font/src/darwin/mod.rs
+++ b/font/src/darwin/mod.rs
@@ -79,7 +79,7 @@ impl Descriptor {
 /// Given a fontdesc, can rasterize fonts.
 pub struct Rasterizer {
     fonts: HashMap<FontKey, Font>,
-    keys: HashMap<(FontDesc, Size), FontKey>,
+    keys: HashMap<(FontDesc, Size, i32), FontKey>,
     device_pixel_ratio: f32,
     use_thin_strokes: bool,
 }
@@ -148,14 +148,14 @@ impl ::Rasterize for Rasterizer {
 
     fn load_font(&mut self, desc: &FontDesc, size: Size) -> Result<FontKey, Error> {
         self.keys
-            .get(&(desc.to_owned(), size))
-            .map(|k| Ok(*k))
+            .get(&(desc.to_owned(), size, (self.device_pixel_ratio * 100.0) as i32))
+            .map(|k| Ok(*k) )
             .unwrap_or_else(|| {
                 let font = self.get_font(desc, size)?;
                 let key = FontKey::next();
 
                 self.fonts.insert(key, font);
-                self.keys.insert((desc.clone(), size), key);
+                self.keys.insert((desc.clone(), size, (self.device_pixel_ratio * 100.0) as i32), key);
 
                 Ok(key)
             })
```

I would have committed that into the repo but I wasn't sure what approach would be best here. With the patch a font size at a particular dpr will only be loaded once (as I didn't clear out the font loaded at the previous dpr). This seems reasonable to me although it obviously requires more memory once you move alacritty to different screens. Another approach would be to just clear the map when the dpr changes.

Let me know which way you would prefer and I can make the changes.

**Comment by chrisduerr** [comment]
Yeah looking at the macOS code it seems like macOS font descriptions directly include the font size instead of just the font description.

This structure should all be very small, so I'd say keeping it around shouldn't be too bad, especially since the user might move it between monitors multiple times and we could re-use the old stuff then.

However looking at it, it should be fine to clear the `keys` map if we would want to, since it's only accessed by `load_font` and everything externally is accessed by `FontKey` instead of description.

We are already doing something similar though, with the `Increase/DecreaseFontSize` bindings we already change the font size, so the `load_font` request will load a new font. I think it's a fair choice to do the same with a DPR change.

The only problem I have with your patch is the way you store the DPR inside the HashMap. Here `* 100` seems like a bit of an arbitrary multiplier. Ideally we should just care about the scaled font size by DPR, so that should be reflected in the key of the HashMap. We are able to create new `Size`s at will and that's exactly the precision we need! So at the beginning of `load_font` I'd calculate a `scaled_size` which is `Size::new(size.as_f32_pts() * self.dpr)`. Like this you don't even need to change the HashMap at all, it just changes the key to store the scaled size instead of the unscaled one.

**Comment by mkeeler** [comment]
Well if we clear the mapping of descriptors/sizes to FontKeys then we would also need to remove those FontKeys from the other fonts map as well. Or else there is going to be a "memory leak" over time. Each time you moved between monitors it would reload an already existing font and assign it to a new FontKey in the fonts map. I think the best route is to scale the size like you mentioned and not change anything else.

**Comment by mkeeler** [comment]
@chrisduerr You have the PR marked with requesting changes. Do you still think other changes need to be made now that the font rendering issue on macos was fixed?

**Comment by petobens** [comment]
@mkeeler I'm still seeing a huge font size when switching monitors. Your latest commit should fix that right?

**Comment by chrisduerr** [comment]
If you look at my review, you can see that it is still relevant. It seems to be an issue with window managers ignoring winit's resize request.

See https://github.com/jwilm/alacritty/pull/1403#pullrequestreview-139270208 for full change request.

**Comment by mkeeler** [comment]
@petobens Try it again if you would. I made one too many modifications with the final bit.

**Comment by petobens** [comment]
Working now :) Thank you so much

**Comment by OkanEsen** [comment]
Yep, working here too, thank you guys very much.

There is one issue though and I'm not sure, if it is related to the padding issue or if it is an issue at all and is working as intended but the height of the content of alacritty between MBP <-> External Monitor seems to differ, after the window was moved from its initial source (alacritty started on external Monitor or MBP) to the destination. 

External monitor:
bildschirmfoto 2018-07-23 um 23 24 12

MBP:
bildschirmfoto 2018-07-23 um 23 24 47

Notice the slightly higher bottom padding in the second screenshot.

**Comment by chrisduerr** [comment]
@OkanEsen I'd assume that this is a combination of the padding not being scaled plus slight rounding issues. Even directly comparing the size in mm of fonts on two different screens often shows slight differences, but they should always be at least in the same ballpark.

I'd assume that the padding will still be fixed in this PR together with the other issue I've mentioned (I'll take a look at this as soon as I've got some time), so once this is solved I'd welcome any further testing! Thanks for pointing this out already though, ideally this should not be the case!

**Comment by chroosh** [comment]
Working well, thanks guys! Although I still get a slower scrolling speed in vim compared to master, not sure what that's caused by.

**Comment by mkeeler** [comment]
@chroosh Are you on MacOS? When testing were you on AC or battery power.

For me I notice quite a speedup of things like resizing windows and scrolling when my MacOS system is using the discrete GPU instead of the integrated intel one. It automatically gets enabled when on AC power which is why I asked about that.

**Comment by chroosh** [comment]
@mkeeler Yep MacOS, I just tested it again on both AC and battery power. Also running on a MBP with only integrated graphics.

**Comment by mkeeler** [comment]
Well my theories are out the window if you mbp doesn't have a discrete gpu.

**Comment by mkeeler** [comment]
The padding issue is turning out to be trickier to fix than expected.

It would seem there are several places we calculate padding sizes. The issues I see are that immediately when I start alacritty the padding is off. The top padding looks like its more than it should be and the bottom is almost nonexistant. The last line in my terminal actually gets cut off by a few pixels. Then when I switch it over to the external monitor the bottom padding gets much bigger. Then when switching back it adds enough room in the terminal to hold a whole other line. This last bit of behavior may be due to rounding. I am not yet sure.

**Comment by chrisduerr** [comment]
@mkeeler See #1190 to help you understand a bit maybe. There's not only the window padding set through the config, but when the number of cells doesn't fit the window size, an additional padding is introduced. There's nothing you can do about this padding and currently it will always be added to the bottom and right side of the terminal.

I hope this is what has been confusing you, otherwise I can take another look at it myself.

**Comment by Clyybber** [comment]
@chrisduerr Would it be possible to introduce an option to balance the  additional padding on the right and left/bottom and top sides so that the text is perfectly centered? This would be a killer feature that all other terminal emulators I know  lack.

**Comment by mkeeler** [comment]
Thanks @chrisduerr. So far I think I have general padding scaling with dpr changes working. The main odd behaviors I am still seeing is that the top padding always seems to look about 50% larger than the bottom padding. This doesn't affect left/right padding which looks equal.

The other behavior I have seen is that when switching from my macbooks internal monitor to external 1080p display and back to the internal display the padding at the bottom appears to be very large. It isn't though. When switching over to the external display calculating the number of lines that can be shown in the display decreases from 24 to 23 lines. Then when switching back it goes back up to 24 lines leaving a lot of space at the bottom of the window. I am not sure if we can or want to do anything about this. One idea would be to try and keep the number of lines/cols the same when switching screens. We would do this only for dpr changes and not for general resizing. I have my doubts about it being very useful in practice though. In the end its just having to round values and it happens to be that for my two screens the same point size doesn't hold the same number of lines.

**Comment by chrisduerr** [comment]
@Clyybber What do you mean by that? The linked PR should always center the content inside the available window, so padding at all sides should be the same. When you say you want the "option", do you mean that you *don't* want that?

@mkeeler The number of cols/lines should always be approximately the same when resizing, however since we deal with conversations from float to integers in the font size, there will always be some loss of precision where a 1.134 DPI is never exactly 1.134 times as big as 1.0. So as far as I can tell it's not possible to make sure the number of lines/columns are always the same, since even though we try to get as close as possible with DPI, this is never exact.

Regarding the issue of the bottom padding always looking about 50% larger than the bottom padding, the bottom padding is most likely to suffer from the grid not being centered inside the window, so it's definitely possible that the bottom padding is significantly bigger. However to work around this for testing it is possible to use unreasonably big paddings with normal cell sizes. If you use a padding of 30 at the top/bottom, it should be clear when the padding isn't calculated properly since a 50% difference would be much, much bigger than just the additional padding introduced by the grid not being centered.

The last issue you've mentioned with the padding changing when moving to a different monitor and back is the only thing where I'm certain that it's not intended behavior. Since DPI changes shouldn't be based off the last DPI but always based off a 1.0 DPI, there shouldn't be any difference based on the DPI the window is coming from. So when it has 24 lines initially and it's moved to a different monitor and only 23 lines are available, it should have 24 lines available again. The padding should always be exactly the same again.

**Comment by chrisduerr** [comment]
@Clyybber That's what I was talking about. The PR I've linked should solve all your worries. (#1190)

**Comment by Clyybber** [comment]
@chrisduerr Thats awesome!

**Comment by mkeeler** [comment]
@chrisduerr my comment may have been misleading. At first I thought the padding size was changing when switching monitors. Then I found out it was just a rounding issue and decreasing the number of rows when moving to the external screen. Alacritty is correctly recalculating the number of lines when moving back to my internal display which results in having an empty line at the bottom of the window to use.

As for the padding differences from top to bottom. This screenshot is indicative of all my problems currently.

alacritty-cut-off

The top padding is somewhat larger (this is with 10px padding) and the last line is being cut-off

**Comment by mkeeler** [comment]
As of now I think the padding scaling issues are taken care of. I grabbed a tool to overlay a pixel ruler on screen and on both screens the padding is just about exactly as set. On my external display the bottom padding is 1 or 2 px larger (I have 30 px padding set) but this is due to rounding and the placement of the grid.

**Comment by mkeeler** [comment]
@chrisduerr I have no way to test out the issue with the tiling WM that you mentioned in your review and when reviewing the code changes I can't think of any reason why the source of the resize event should matter much.

**Comment by chrisduerr** [comment]
@mkeeler I can look into fixing the tiling WM issues myself this weekend, I might be able to update this issue with more information if I don't get around to fix it myself.

I'll also try to test the padding while I'm already at it.

**Comment by chrisduerr** [comment]
So I've looked into the issue with resizing and I've found the problem.

The issue is caused by me moving a window to a different screen, which resizes the window and changes the DPI at the same time. The resize event however is still sent with the old DPI, so basically when the window is moved to the new screen, it is first resized and then the DPI is changed, causing the resize event to have a DPI which is not accurate. As a result of this the physical size of the window is reported as 2954x1610 on a 2560x1440 display.

Here's some debug output I've captured which should show this issue:
```bash
# This is the initial size on a display with 1.0 DPI
NEW SIZE: LogicalSize { width: 619.0, height: 1020.0 }
NEW SIZE PHYS: PhysicalSize { width: 619.0, height: 1020.0 }
# Moving the window to a 2560x1440 display with 1.1666... DPI
NEW SIZE: LogicalSize { width: 2532.0, height: 1380.0 }
NEW SIZE PHYS: PhysicalSize { width: 2954.0, height: 1610.0 }
# Expected value would be PhysicalSize { width: 2532.0, height: 1380.0 }
```

This issue can be solved by sending a `PhysicalSize` to the `handle_event` method in `src/display.rs` instead of sending a `LogicalSize` and using the dpr at the point in time when the resize event is processed. This way there's no racing condition with a HIDPI change event since all events are processed in order..

@mkeeler You can find my implementation to fix this problem here:
https://github.com/chrisduerr/alacritty/tree/glutin-0.17-upgrade

If you have any comments on the commit I've added, please let me know. Otherwise feel free to just pull in my latest commit into this PR.

File: src/display.rs [hunk 2]
```diff
@@ -163,11 +163,11 @@ impl Display {
             let height = cell_height as u32 * dimensions.lines_u32();
 
             let new_viewport_size = PhysicalSize::new(
-                (width + 2 * u32::from(config.padding().x)) as f64,
-                (height + 2 * u32::from(config.padding().y)) as f64);
+                (width + 2 * u32::from(config.padding().x) * dpr.floor() as u32) as f64,
+                (height + 2 * u32::from(config.padding().y) * dpr.floor() as u32) as f64);
```
Comment (chrisduerr) [inline src/display.rs]: I feel like this might produce slightly incorrect results, why are you flooring the DPR here before finishing the calculation? Also the result itself seems to be `f64` so I'm not sure why everything's converted to whole numbers (even before the change you've made).

`width as f64 + 2. * config.padding().x * dpr` seems like the calculation we'd want to do here. And just in case the padding is converted to u32 (floored basically) because we need a padding that is smaller than the available pixels (we wouldn't want to round up a padding since it would reduce the terminal area), then something like this should be more appropriate:
`(width + 2 * u32::from(config.padding().x * dpr)) as f64`

Note that the latter version also is in line with the changes you've made in the renderer, I'd assume this might just have been accidental? If there is a reason for this, please let me know.

Comment (mkeeler) [reply src/display.rs]: Totally an accident after many iterations of going back and forth trying to get it to work.

**Comment by mkeeler** [comment]
@chrisduerr The commit looked good so I pulled it in. I can see how this practically works but also seems like there could be a bug in the window manager or in winit. It sounds like the window manager is resizing the window to larger than the screen its currently on and then moving the screen. When the screen change occurs the dpi is updated. It seems like the underlying problem is the WM isn't accounting for DPI when calculating what resolution to resize to.

Regardless, sometimes you have to account for platform differences and bugs.

**Comment by mkeeler** [comment]
@chrisduerr what else at this point needs to happen prior to getting this merged?

**Comment by chrisduerr** [comment]
@mkeeler The review comment I've added about the rounding of the padding is still unsolved. Once that's fixed I think the state of this PR is good, even though some more testing on different platforms with different DPIs might be nice.

I suspect this will only be merged after scrollback though, which hopefully can be done relatively soon.

File: src/display.rs [hunk 3]
```diff
@@ -163,8 +163,8 @@ impl Display {
             let height = cell_height as u32 * dimensions.lines_u32();
 
             let new_viewport_size = PhysicalSize::new(
-                (width + 2 * u32::from(config.padding().x) * dpr.floor() as u32) as f64,
-                (height + 2 * u32::from(config.padding().y) * dpr.floor() as u32) as f64);
+                width as f64 + 2. * config.padding().x as f64 * dpr,
+                height as f64 + 2. * config.padding().y as f64 * dpr);
```
[the remark this answers is not in the document]
Comment (mkeeler) [reply src/display.rs]: I agree and am finishing up those changes now.

The general goal being where the padding is scaled to multiply padding * dpr and then round towards 0 before using it further.

**Comment by mkeeler** [comment]
Okay all the padding should be correct now. Things look correct at least on macos and the calculations regarding the padding should be uniform. The general goal was where a scaled padding value was needed the base padding would be converted to a float if need be, multiplied by the dpr and then floored. The flooring could be accomplished either with an integer conversion or with an explicit floor call.

Then the whole number would be used in the rest of the calculation.

**Comment by chrisduerr** [comment]
Functionality looks great now! There's just a few clippy issues I've noticed.
See [here](https://paste.rs/Mvc) for a full list of issues introduced by this PR.

Currently there's a bug in clippy, so you'll have to `#![cfg_attr(feature = "cargo-clippy", allow(redundant_field_names))]` and since there have been some clippy fixes in the master branch, you'll have to rebase on master, but after that it should be good to go.

**Comment by OkanEsen** [comment]
I just tested the newest state and something seems to be wrong. Moving the window from my external monitor to the internal display looks like this:

External monitor:
bildschirmfoto 2018-08-04 um 22 22 57

MBP:
bildschirmfoto 2018-08-04 um 22 22 52

The weird thing is, if I move the window between both it kinda fixes itself and breaks again if I move it again. See this video where you can obviously see only my external monitor, where I move the window between both monitors: https://mnemo.okanesen.com/LWYS/alacritty-glutin17-wrong-padding.mov

**Comment by mkeeler** [comment]
Interestingly enough I can sometimes reproduce that problem.

If I move the window back and forth between two monitors quickly eventually it runs into that rendering issue.

@chrisduerr If I revert your commit then I cannot reproduce at all.

**Comment by chrisduerr** [comment]
@mkeeler That might be the case, but we don't need to process DPI events to get the right DPI. If there's a DPI event that hasn't been processed yet, the `get_hidpi()` method which is used to convert the resize event to a physical size is still accurate, it doesn't need to be processed first.

The only way the resize event could have the wrong DPI is if there's a new dpi change between the time the event is sent and the time the event is processed and converted to physical sizes. It should be possible to test this and if it is indeed the case, this will probably need to be fixed in winit.

I'd assume that adding the `dpi_factor` to the resize event in winit would fix this issue if this is indeed a racing condition.

**Comment by mkeeler** [comment]
My logic probably wasn’t right. It happened to me when using an external 4K display and my mbp screen. Both of which macOS gives a 2.0 dpi to. So no dpi change. Which probably gets rid of the possibility of it being directly related to your commit.

**Comment by chrisduerr** [comment]
Getting the output of `-vvv` might be interesting in this case. With Alacritty being moved from a 2.0 DPI screen to a 2.0 DPI screen, nothing should change.

I wonder if this is related to the dpr adjustment in the font subcrate. Since I'm not running into these issues on Linux. Unless there's some really specific setup required, just moving windows from one screen to another works great with my displays.

**Comment by OkanEsen** [comment]
Here is a video with debug output: https://mnemo.okanesen.com/imTK/alacritty-glutin17-padding-2-vvv.mov

The setup is the same (MBP <-> External Monitor).

**Comment by jacoscaz** [comment]
I'm on Mac OS. I can successfully compile (`make app`) the `glutin-0.17-upgrade` but the resulting application crashes with the following:

```
thread 'main' panicked at 'The `scale_with_dpi` field has been deprecated, on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.', src/config.rs:1563:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With `RUST_BACKTRACE=1` I get the following:

```
thread 'main' panicked at 'The `scale_with_dpi` field has been deprecated, on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.', src/config.rs:1563:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: alacritty::config::deserialize_scale_with_dpi
   6: serde_yaml::de::Deserializer::visit
   7: <&'r mut serde_yaml::de::Deserializer<'a> as serde::de::Deserializer<'de>>::deserialize_any
   8: alacritty::config::failure_default
   9: serde_yaml::de::Deserializer::visit
  10: <&'r mut serde_yaml::de::Deserializer<'a> as serde::de::Deserializer<'de>>::deserialize_any
  11: serde_yaml::de::from_str
  12: alacritty::main
  13: std::rt::lang_start::{{closure}}
  14: main
```

I did look around for this but couldn't find anything, so I thought it'd be worth mentioning. More than happy to help testing!

**Comment by chrisduerr** [comment]
`The 'scale_with_dpi' field has been deprecated, on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.`

Is there any way we should improve this error? It seems quite straight-forward to me that it requires removing the `scale_with_dpi` field from the config. But if there is any way to make this even more clear, please let me know.

**Comment by jacoscaz** [comment]
@chrisduerr I now obviously feel like an idiot (and rightfully so). However, if you guys were to change `field` to something like `setting` or `configuration option`, I bet this would help a few others not to feel like idiots... 

As my configuration file was created and populated *automatically* by `Alacritty` (`master` branch on the main repo), I did not stop to think the same config file could also be breaking the app.

That said, I am now able to test the `glutin-0.17-upgrade` branch and it looks like it resolved all issues I had with HiDPI. I'm working with two monitors, a 1920x1200 DELL (no retina) and my 2013 MacBook Pro's monitor, which is normally set at 1280x800 (2x retina) although I keep it at 1440x900.

**Comment by chrisduerr** [comment]
It would be possible to start Alacritty even with the flag enabled and just emit a warning that it is not supported anymore. IIRC I opted for the error to make it clear that the config option is not supported anymore, however I don't think that was the right choice.

Changing the warning to make it obvious it's coming from a configuration option also seems like a good idea. Thanks for the feedback @jacoscaz.

**Comment by mkeeler** [comment]
@chrisduerr 

I Rebased to Master, upgraded to Glutin 0.18 and Winit 0.17 and fixed almost all the Clippy warnings.

The one remaining non-buggy clippy warning is about the deserialization of the scale_with_dpi config item.

**Comment by chrisduerr** [comment]
Great work @mkeeler, I think in the remaining issue it would be perfectly fine to just locally ignore the problem. Macros can sometimes mess with clippy a bit.

**Comment by mkeeler** [comment]
@chrisduerr I am still trying to figure out the macos issue that @OkanEsen is seeing and that I saw once but am unable to reproduce currently.

In the commit I just pushed I fixed to make the scale_with_dpi config emit a warning instead of panicing. How I had to implement this also had the side effect of getting rid of the clippy warning regarding that deserialize function.

I slightly altered the text of the warning message (one word). Feel free to change it more if you have better ideas.

As for the last item, I think the only remaining clippy warnings are those regarding the buggy redundant_field_names. How would you propose ignoring those? Should that lint be disabled in lib.rs or should it be disabled just for those functions where its a problem?

File: src/config.rs [hunk 4]
```diff
@@ -1590,13 +1590,15 @@ pub struct Font {
...
-    panic!(
-        "The `scale_with_dpi` field has been deprecated, \
-         on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead."
-    );
+    // This seems to be necessary in order for the config containing this entry to be parsed properly
+    let _ignored = bool::deserialize(deserializer);
+    eprintln!(
+        "The `scale_with_dpi` setting has been removed, \
+        on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.");
+    Ok(None)
```
Comment (chrisduerr) [inline src/config.rs]: To fall in line with the other warnings we have, this warning should be a yellow color.

The comment about the `_ignored` variable also could be improved a bit. If it really is necessary, changing it to `// This is necessary on order for ...` seems to be a better choice.

The warning message itself seems fine to me.

Comment (mkeeler) [reply src/config.rs]: Well the other config file warnings just use the `eprintln!` macro (and are not colored). My first pass was to use the `warn!` macro but logging isn't initialized when the config is being parsed. 

As for the comment about _ignored its not super clear why it should be required. All I know is that if that deserialize function doesn't do that then the following error is emitted and the whole configuration file seems to be ignored:

```
problem with config: font: invalid type: boolean `true`, expected field identifier at line 80 column 19; Using default value
Error: problem with config: deserializing from YAML containing more than one document is not supported; Loading default config
```

The serde docs for the attributes don't mention requiring that you actually attempt to deserialize anything: https://serde.rs/field-attrs.html#serdedeserializewith--path

However I wouldn't be surprised if it was expected and just not made explicit in the docs.

Comment (mkeeler) [reply src/config.rs]: I updated the comment to say `// This is necessary in order to get serde to complete deserialization of the configuration`

Its probably better than the first pass but still not particularly informative. Without digging into a bunch of serde internals I don't have any other way of knowing why its happening or if its maybe a bug in serde.

Comment (chrisduerr) [reply src/config.rs]: > Well the other config file warnings just use the eprintln! macro (and are not colored). My first pass was to use the warn! macro but logging isn't initialized when the config is being parsed.

See https://github.com/jwilm/alacritty/blob/master/src/config.rs#L991-L995.

> As for the comment about _ignored its not super clear why it should be required.

Try changing the type to `Option<bool>` instead of `Option<()>`.

Comment (mkeeler) [reply src/config.rs]: The warning has been made yellow.

I tried using `Option<bool>` & `bool`. When trying `Option<bool>` I also tried returning `Ok(None)` and `Ok(Some(true))`. Nothing seems to work. If the _ignored line gets commented out the config fails to parse.

Comment (mkeeler) [reply src/config.rs]: Would you still prefer an `Option<bool>` over the `Option<()>` even if it makes no functional difference?

**Comment by mkeeler** [comment]
For the macos rendering issue, I found its much easier to reproduce if I take a screen recording at the same time.

I assume there is a race condition that we just happen to be hitting when other processes on the system are using the CPU/GPU (like when screen recording).

Also it does seem to require different DPR monitors in order to make it happen. With `-vvv` the logs mine produced follows (with some carriage return linefeed logs removed)

```
Welcome to Alacritty.
Configuration loaded from /Users/mkeeler/.config/alacritty/alacritty.yml
device_pixel_ratio: 2
width: 2048, height: 1536
Initializing glyph cache
Finished initializing glyph cache in 0.109036759

### This is where we are force resizing down the the lines/cols in the config
width: 1292, height: 852
Cell Size: (16 x 35)
PTY Dimensions: Line(24) x Column(80)
Font size changed: Size(32) [DPR: 2]
Term::resize
Term::resize dimensions unchanged
width: 1292, height: 852

# switching to external display running with a 1600x900 resolution
Font size changed: Size(32) [DPR: 1]
Term::resize
# after rounding etc. the number of lines gets reduced by one - not a big deal
num_cols, num_lines = 80, 23
# same general size = 1/2 of the DPR = 2 size
width: 646, height: 426

# switching back to internal monitor
Font size changed: Size(32) [DPR: 2]
Term::resize
# this is wrong - cols/lines should go back to 80/24
num_cols, num_lines = 39, 11
# this is also wrong - the physical width/height should go back to the 1292x852 size
width: 646, height: 426
```

**Comment by mkeeler** [comment]
@chrisduerr I fixed at least the issue my debugging showed. The crux of the problem went like:

1. `process_events` waits on glutin events and pushes them into the Vec
2. `window.hidpi_factor()` is used to get the dpr of the window (this returns an unexpected value of the dpr of the old screen
3. `handle_event` is called on a HiDpiFactorChanged event (the dpr in the event is different than the dpr we grabbed from the `hidpi_factor` call)
4. `handle_event` is called and we passed in the cached but incorrect dpr to use to scale the logical size to a physical one.

The fix was to make the dpr passed into handle_event a `&mut` and then receiving the HiDpiFactorChanged event now will update that dpr. 

Give it a shot with your window manager to make sure it doesn't break anything that way.

@OkanEsen Could you give the latest code a try to ensure it fixes what you were seeing as well?

**Comment by chrisduerr** [comment]
Even though it took me a bit, I think I understand now why the previous two iterations did not work but this one did. Loads of racing condition stuff going on, but I'd say this looks pretty good.

I'm just concerned with the maintainability of this code, reading it now it makes sense to mutate a reference, which is used in the `Resized` method, however it is kinda complex. It's not directly apparent why the `dpr` is mutated and you have to understand that `handle_event` is called multiple times with `Resized` making use of the mutated `dpr`.

I would propose the following patch for simplifying this. Instead of having a separate `dpr` field which is passed to the method and mutated, the `size_info` on the context is now used to keep track of the current DPI.

<details>

```diff
diff --git a/src/event.rs b/src/event.rs
index 80690ed..2526354 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -35,7 +35,7 @@ pub struct ActionContext<'a, N: 'a> {
     pub notifier: &'a mut N,
     pub terminal: &'a mut Term,
     pub selection: &'a mut Option<Selection>,
-    pub size_info: &'a SizeInfo,
+    pub size_info: &'a mut SizeInfo,
     pub mouse: &'a mut Mouse,
     pub selection_modified: bool,
     pub received_count: &'a mut usize,
@@ -286,7 +286,6 @@ impl<N: Notify> Processor<N> {
         resize_tx: &mpsc::Sender<PhysicalSize>,
         hide_cursor: &mut bool,
         window_is_focused: &mut bool,
-        dpr: &mut f64,
     ) {
         match event {
             // Pass on device events
@@ -318,7 +317,7 @@ impl<N: Notify> Processor<N> {
                         ::std::process::exit(0);
                     },
                     Resized(lsize) => {
-                        resize_tx.send(lsize.to_physical(*dpr)).expect("send new size");
+                        resize_tx.send(lsize.to_physical(processor.ctx.size_info.dpr)).expect("send new size");
                         processor.ctx.terminal.dirty = true;
                     },
                     KeyboardInput { input, .. } => {
@@ -377,7 +376,7 @@ impl<N: Notify> Processor<N> {
                         processor.ctx.write_to_pty(path.into_bytes());
                     },
                     HiDpiFactorChanged(new_dpr) => {
-                        *dpr = new_dpr;
+                        processor.ctx.size_info.dpr = new_dpr;
                         processor.ctx.terminal.dirty = true;
                     },
                     _ => (),
@@ -431,7 +430,7 @@ impl<N: Notify> Processor<N> {
                 notifier: &mut self.notifier,
                 selection: &mut self.selection,
                 mouse: &mut self.mouse,
-                size_info: &self.size_info,
+                size_info: &mut self.size_info,
                 selection_modified: false,
                 received_count: &mut self.received_count,
                 suppress_chars: &mut self.suppress_chars,
@@ -447,8 +446,7 @@ impl<N: Notify> Processor<N> {
             };
 
             let mut window_is_focused = window.is_focused;
-            let mut dpr = window.hidpi_factor();
-            
+
             // Scope needed to that hide_cursor isn't borrowed after the scope
             // ends.
             {
@@ -464,7 +462,6 @@ impl<N: Notify> Processor<N> {
                         resize_tx,
                         hide_cursor,
                         &mut window_is_focused,
-                        &mut dpr,
                     );
                 };
```
</details>
​

This approach should have the same effect as the current version, however this raises a question about updating multiple different versions of `SizeInfo`. Currently there are three different versions of `SizeInfo`. We have one in the processor context for events, one in the display.rs and one in the Term. So whenever DPR is updated now, the processor's `SizeInfo` is updated first, then the display.rs asks the window separately for the current dpr and then tells the Term and the processor context about the new size information. I'd say this is slightly suboptimal, especially the part where the Display is updating the context's size_info after it has already updated itself.

Ideally it would be great to pass `Display` to the `handle_event` method, so we could just use the `Display`'s `SizeInfo` in the event. This would also allow removing things like the `window_is_focused` method. However it's not possible to easily do that since it leads to a double mutable borrow issue.

I don't think this needs to be solved with this PR, I think my fix isn't too bad and slightly improves the current version in this PR. However if you have a better idea how to do this @mkeeler, I'm open for ideas!

**Comment by mkeeler** [comment]
@chrisduerr Using the DPR from the `ActionContext` makes sense. My only concern would have been that this didn't produce the desired results on your system as we are using a potentially longer lived cache of the DPR in the `size_info` of the processor rather than grabbing it immediately prior to processing the individual events. On MacOS its kind of a non-issue so long as winit keeps sending the `HiDpiChangedEvent` prior to a resize as the `ActionContext` will have the dpr get updated at the time of processing events regardless.

**Comment by mkeeler** [comment]
@chrisduerr should all the scrollback work fix the terminal output shrinking?

I do notice when I go from one screen (hidpi) to another (non-hidpi) and back that after all the rounding I lose a line of terminal output. It makes sense why it happens but I assume if there was a scrollback buffer when resizing we would fill all the lines of the screen if we had enough in the buffer.

**Comment by chrisduerr** [comment]
@mkeeler No, scrollback will not fix this issue, however I do think it makes sense to open a separate issue for this.

See #1502.

**Comment by OkanEsen** [comment]
Just tested the latest changes and the issues I had are fixed. Thank you very much guys!

There is still that rounding error with the padding but that issue is really minimal and nitpicky.

**Comment by petobens** [comment]
Hi @chrisduerr, I've recently switched from Mac to Arch and i3 and I cannot getting resizing to work properly (from the replies above I gathered that you use i3 yourself). With the following binding in my i3 config
```
set $nexec exec --no-startup-id
bindsym $mod+Ctrl+n exec alacritty -t numbers -e ipython3
for_window [title="^numbers"] floating enable, resize set 400 400, move position center
```
I expect that when alacritty opens it does so as a centered floating window with dimensions 400x400. However when i run the binding the alacritty windows gets open with a way larger size that spans my two monitors:

screenshot_2018-08-11_15 56 48

Can you reproduce this? In general: should i3's `resize set` work properly with alacritty or is it a known problem?

Note: i'm reporting this here because i'm using this branch.

**Comment by chrisduerr** [comment]
@petobens Since Alacritty requests a resize at startup, setting the size through i3's `resize set X Y` is not possible afaik. However there's still a way to do this.

Try the following:
```
bindsym $mod+Ctrl+n exec alacritty -t numbers --dimensions 100 25 -e sh -c \
    "i3-msg move position center && ipython3"
for_window [title="^numbers"] floating enable
```

The `--dimensions` option allows you to specify width and height in lines and columns not pixels and is also supported in the config, if you want to do it in pixels, you can add another `i3-msg` command.

If you have any more questions about this, please feel free to hit me up on freenode's #alacritty or open a separate issue.

**Comment by iwata** [comment]
Hi, @chrisduerr 
I built `mkeeler:glutin-0.17-upgrade` on manual and tried it.
But it did not accelerate with eGPU.
Those who build the current `HEAD` branch can use eGPU without any problem, but have problems that you are not yet able to deal with?

**Comment by iwata** [comment]
@chrisduerr @mkeeler 
I'm sorry, I'm misunderstanding about eGPU.
eGPU is irrelevant, just rendering was delayed if this branch's build.
I tried out the eGPU and tried it, the result did not change so I want you to forget about eGPU.

> Also did you install the Alacritty.app bundle or are you just executing the binary directly?

I'm using via Alacritty.app bundle.

**Comment by iwata** [comment]
@mkeeler 

> if using an integrated gpu vs the discrete gpu rendering will be slower.

I know. But there was no noticeable speed difference between them.
So the matter of eGPU does not matter.

What I am concerned about is that if I try this branch's build, rendering delay will occur, it's independent on eGPU.

**Comment by mkeeler** [comment]
@sodiumjoe Try again. I found a typo in that commit within the update_projection function on the renderer.

This is what was in that commit
```
let ortho = cgmath::ortho(
            0.,
            width - (2. * padding_x),
            2. * padding_x,
            height,
            -1.,
            1.,
        );
```
The problem with it is that `2. * padding_x` as the third arg to ortho should be `2. padding_y`

**Comment by sodiumjoe** [comment]
@mkeeler looks great now, thanks!

**Comment by bpierce1** [comment]
I've tried this branch on my machine, os x is still reporting Alacritty using significant energy. Is this branch supposed to solve that problem?

**Comment by mkeeler** [comment]
What this branch fixes is to allow automatic graphics switching on macOS so it takes less energy and when on battery power the activity monitor energy tab should show alacritty as not requiring the high perf gpu and hopefully (unless you are running other apps that require the high perf gpu) will remain using the integrated gpu. It does require installing the .app bundle as the included plist tells the os that it should be allowed.

**Comment by bpierce1** [comment]
I see, thanks for the explanation! Sorry for the early report. While the little "apps using significant energy" icon does show Alacritty, looking into Activity Monitor shows you're right: it doesn't require high perf GPU. And in fact, it's using ~1/10 the "Energy Impact" of chrome.
Thanks!

**Comment by sodiumjoe** [comment]
fyi, i have a PR into winit to patch bump: https://github.com/tomaka/winit/pull/630

Hopefully we can wait for that before merging this?

**Comment by mkeeler** [comment]
@sodiumjoe will it also require a glutin 0.18.1?

**Comment by chrisduerr** [comment]
@mkeeler Updates that should be safe based on semver should work without any issue. So glutin says that it requires `0.17.0` for example, which means it's fine with `0.17.0` until `0.17.99999...`. So an update to `0.17.2` will not require that we update glutin. How exactly this works can be seen in the `cargo` web documentation [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).

Also this PR is only so much work because it's a minor bump instead of a patch, so it introduces API breakage (after 1.0 this would be a major). So a simple patch from `0.18.0` to `0.18.1` should not require any changes to Alacritty (otherwise it conflicts with semver). So we should be clear for a while.

**Comment by chrisduerr** [comment]
I've updated glutin to `0.17.2` and as a result the smithay-client-toolkit was bumped to `0.3.0` as a result of that. Hopefully should be all good and all the issues added in the original comment should be fixed by this PR now.

**Comment by sodiumjoe** [comment]
Anything left for this to merge, @chrisduerr ?

**Comment by chrisduerr** [comment]
@sodiumjoe It's looking good as far as I'm concerned. But since it's quite a significant merge that might cause some conflicts it will be merged after scrollback.

Some additional testing is always welcome but I wasn't able to find any other issues with this.

**Comment by sodiumjoe** [comment]
Great! So, uh, anything left for scrollback to merge?

**Comment by chrisduerr** [comment]
@sodiumjoe Nope, I'd expect scrollback to be merged soon.

**Comment by petobens** [comment]
Hi, I recently switched to a HiDPI laptop and I'm having some trouble with this
again.  My HiDPI laptop screen has a 3000x2000 resolution and my HDMI monitor a
resolution of 1920x1080. I manage this multimonitor setup with xrandr by
running:
```
xrandr --output DP1 --scale 2x2 --auto --pos 0x0 --output eDP1 --primary --dpi 192 --pos 3840x0
```
(i.e my HiDPI laptop screen is to the right the HDMI monitor)

I use the following font setup which looks great on the HiDPI screen:
```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: SourceCode Pro
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 8.5
```
However when I drag a floating Alacritty window from the HiDPI screen to the HDMI
screen  the font looks tiny and in order to be able to use it I must increase
the zoom level several times.

For the record this is what Alacritty records when moving the window from one
monitor to the another

```
Font size changed: Size(17) [DPR: 2.6666666666666665]
Term::resize
num_cols, num_lines = 61, 18
width: 1122, height: 726
Term::resize
num_cols, num_lines = 82, 25
width: 1496, height: 968
Font size changed: Size(17) [DPR: 2]
Term::resize
num_cols, num_lines = 106, 34
width: 1496, height: 968
Term::resize
num_cols, num_lines = 79, 25
width: 1122, height: 726
```
Note that the `DRP: 2.66` is on my HiDPI screen and the `DPR:2` on my HDMI one.
Something is a bit off right?
Thanks once again for the help!

PS: @chrisduerr I'm on Arch Linux using i3. All my tests have been with floating windows
(i.e not tiled)

**Comment by petobens** [comment]
Thanks for the quick reply @chrisduerr. This is the output from `xrandr`:
```
Screen 0: minimum 8 x 8, current 6840 x 2160, maximum 32767 x 32767
eDP1 connected primary 3000x2000+3840+0 (normal left inverted right x axis y axis) 290mm x 200mm
   3000x2000     60.00*+  48.01
DP1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     60.00*+  50.00    59.94
   1920x1080i    60.00    50.00    59.94
   1680x1050     59.88
   1400x1050     59.95
   1600x900      60.00
   1280x1024     60.02
   1440x900      59.90
   1280x800      59.91
   1152x864      59.97
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   800x600       60.32
   720x576       50.00
   720x480       60.00    59.94
   640x480       60.00    59.94
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```
> So this should be fixed in xorg

What do you mean by this? Should I change something in the `xrandr` command that defines the multimonitor setup?
Once again thanks for help.

**Comment by chrisduerr** [comment]
If the physical sizes are correct, the calculated DPI should be correct.

And if the calculated DPI is correct, I don't see how they would be different on monitors with a different size. Have you tried disabling all scaling in Xorg?

**Comment by petobens** [comment]
I disabled scaling with:
```
xrandr --output DP1 --scale 1x1 --auto --pos 0x0 --output eDP1 --primary --pos 1920x0
```
and now alacritty gives the following output when moving a window from my HiDPI screen to the HDMI monitor:
```
Font size changed: Size(17) [DPR: 2.6666666666666665]
Term::resize
num_cols, num_lines = 52, 13
width: 956, height: 536
Term::resize
num_cols, num_lines = 141, 37
width: 2549, height: 1429
Font size changed: Size(17) [DPR: 1]
Term::resize
num_cols, num_lines = 363, 101
width: 2549, height: 1429
Term::resize
num_cols, num_lines = 136, 38
width: 956, height: 536
```
Shouldn't the scale factor (is that the DPR?) be the other way round? I mean when moving from the HiDPI to the lower resolution HDMI monitor things should scale up (not down) right? (I'm just guessing here).
Thanks for following this through.

**Comment by chrisduerr** [comment]
The DPI is a scale factor by which the window size should be increased. So a DPI of 3.0 will increase the size of the window and all text by a factor of 3.

If winit/glutin applies DPI scaling and then you manually scale everything up again, it will lead to winit/glutin windows being scaled twice. If you want Alacritty to always use a fixed DPI, you can use `WINIT_HIDPI_FACTOR=1 alacritty`. But as far as I can tell right now I don't think Alacritty is doing anything wrong.

**Comment by petobens** [comment]
Using a fixed DPI seems to solve all my problems. Thanks!

**Comment by sodiumjoe** [comment]
looks like we need a merge or rebase now that scrollback has been merged

**Comment by Byron-TW** [comment]
@sodiumjoe Just because I have been eyeballing this PR for a while now, I have done the merge of this branch back to master locally. Except for a single, trivial conflict which I was able to resolve, it compiles just fine.
However, now that alacritty doesn't trigger the high-performance graphics anymore, it feels extremely sluggish when typing. Interestingly, and thanks [the latest blogpost](https://jwilm.io/blog/alacritty-lands-scrollback/), I could verify that this sluggishness is not due to performance degradation - it's exactly as fast as master.

Maybe @mkeeler has an idea?

<details>
screen shot 2018-09-17 at 19 27 23
</details>

**Comment by mkeeler** [comment]
I resolved the conflicts with master.

@Byron-TW Your laptop doesn't have a discrete radeon gpu right (doesn't look like it according to the image posted). And there is a perceived increase in latency between pressing a key and it showing up on the screen?

**Comment by Byron-TW** [comment]
@mkeeler My system does indeed have a discreet GPU, it's default for all 15-inch macbooks. Thanks to your comment, I was able to reproduce the issue consistently. After a graphics switching occours, Alacritty lags noticeably. There it doesn't matter if the GPU goes from performance to integrated, or the other way around.

**A workaround** 🎉seems to be to just resize the window, which will restore the original performance.

Did you notice that the window resizing is extremely slow on integrated, and noticeably slower on performance mode compared to alacritty without the patch?

**Comment by mkeeler** [comment]
@Byron-TW I did notice that resizing is noticeably slower on integrated graphics. Since the very first commit to this PR it has been that way.

Resizing on integrated in this branch compared to alacritty master isn't a fair comparison. alacritty master will always use the discrete GPU which was my initial motivation for patching glutin and then alacritty. When using the discrete GPU I didn't notice any difference.

I wonder if resizing internally causes something with glutin/winit or the underlying NSView on macos to update and pick up the changes that the GPU has changed?

It will take some more digging to get to the bottom of this.

**Comment by SirCmpwn** [comment]
This is a looong thread - I apologise if I'm saying something which has already been pointed out. I tested this branch on sway master (with wlroots) and a mixed-DPI setup. If I run alacritty on the lodpi (scale=1) display, everything works normally. If I run it on a hidpi display, however, I see the following behavior:



Resizing the terminal or switching focus fixes the issue.

Additionally, when opening alacritty on a hidpi display and dragging it to a lodpi display, or vice versa, the alacritty window shows at 2x or 0.5x size, though the font is still shown correctly and the window borders are correct.

Otherwise everything works great :) thanks for your hard work!

Note, I was running this branch with this other pull request merged into it: https://github.com/jwilm/alacritty/pull/1518

**Comment by chrisduerr** [comment]
Thanks for reporting back with wayland @SirCmpwn. I believe until now this has mainly been tested on i3 and macOS.

I'm not completely certain which issue you're trying to point out with the screenshot. Is that Alacritty's window borders at the top? So is the window size growing, but Alacritty isn't filling in its size? Does typing fix this issue? If it doesn't, what happens when you type enough text for filling the complete line. I'm curious if Alacritty is actually smaller or if the background just hasn't been redrawn.

Being able to switch windows between displays with proper DPI rescaling has also been a main focus of this PR, so it's surprising that it still seems to have so much issues on Wayland. What do you mean by `the alacritty window shows at 2x or 0.5x size`? If borders and font size are correct, what else is there that needs to be scaled? Are the window decorations not scaled properly or is it something else?

Also would probably be interesting to hear if @francesca64 has heard anything about Wayland not properly resizing when switching windows. It sounds like this might be a winit problem?

**Comment by vberger** [comment]
@chrisduerr I believe this is a very simple issue. Under wayland, glutin's user is responsible for resizing its contents using the `GlContext::resize` method. (winit can handle the resizing of the borders itself, but not the resizing of the contents, du to wayland's design).

If looks like alacritty does this inconsistently: it does it correctly on resize, but not on DPI change.

**Comment by SirCmpwn** [comment]
>Is that Alacritty's window borders at the top? So is the window size growing, but Alacritty isn't filling in its size?

Yes

>Does typing fix this issue? If it doesn't, what happens when you type enough text for filling the complete line. I'm curious if Alacritty is actually smaller or if the background just hasn't been redrawn.

Typing doesn't fix the issue. Alacritty is actually smaller afaict.

>What do you mean by the alacritty window shows at 2x or 0.5x size? If borders and font size are correct, what else is there that needs to be scaled?

The font size and so on are correct - the actual terminal window is 2x larger or smaller than the window borders, and than the appropriate size given its size before.

This stuff should be pretty easy for you guys to test. Sway can be run on a virtual output as an X11 window inside of your usual workflow. You can add this to the default config file to set the scale factor of the virtual output:

```
output X11-1 scale 2
```

You can get multiple outputs by setting `WLR_X11_OUTPUTS=2` before starting sway. Otherwise it behaves identically to i3.

**Comment by chrisduerr** [comment]
@vberger Thanks for the heads-up. I'll look into it when I've got some time unless @mkeeler managed to figure it out before me.

**Comment by vberger** [comment]
So, I managed to make it work by applying the following diff on top of this PR merged with #1518:

```diff
diff --git a/src/event.rs b/src/event.rs
index 258867a..24dc470 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -387,7 +387,15 @@ impl<N: Notify> Processor<N> {
                         processor.ctx.write_to_pty(path.into_bytes());
                     },
                     HiDpiFactorChanged(new_dpr) => {
+                        let old_size = ::glutin::dpi::PhysicalSize {
+                            width: processor.ctx.size_info.width as f64,
+                            height: processor.ctx.size_info.height as f64,
+                        };
+                        let lsize = old_size.to_logical(processor.ctx.size_info.dpr);
                         processor.ctx.size_info.dpr = new_dpr;
+                        resize_tx
+                            .send(lsize.to_physical(processor.ctx.size_info.dpr))
+                            .expect("send new size");
                         processor.ctx.terminal.dirty = true;
                     },
                     _ => (),
```

The idea is that `HiDpiFactorChanged` events are then handled as if they where also `Resized` events. This fixes alacritty having a wrong initial size on my hidpi display. I can't test multiple monitors though.

I guess the main question is to ensure this does not have unintended consequences on other platforms.

**Comment by chrisduerr** [comment]
@vberger Thanks for looking into this!

I gave this patch a quick shot on linux/x11/i3 and I've noticed that this introduces a regression when it comes to moving windows between displays.

This is the exact same issue that I have previously mentioned in this thread. It only happens with i3 when the window is in tiling mode, not when it's floating. I'm not quite sure if this can be solved by just reverting the fix for this issue, or if the fix has to be applied on DPI changes too now. I might be able to look into this tomorrow, but I'd imagine with the previous change in mind this shouldn't be impossible to fix.

**Comment by chrisduerr** [comment]
So here's an explanation why this is currently not working:

When a resize and DPI event comes in at the same time, with the resize event coming first, the DPI event will queue a resize event which scales the old resize event scaled by the new DPI. However it should instead take the latest screen size even when it hasn't been processed yet.

I would instead propose handling this in the `handle_resize` method in `src/draw.rs`, since that is synchronous and we know about all previous resize actions.

I wasn't able to test this on sway, however I would propose this patch:
<details>

```diff
diff --git a/src/display.rs b/src/display.rs
index 3d71631..14a8947 100644
--- a/src/display.rs
+++ b/src/display.rs
@@ -293,19 +293,19 @@ impl Display {
         // Font size/DPI factor modification detected
         if terminal.font_size != self.font_size || (dpr - self.size_info.dpr).abs() > f64::EPSILON {
-            self.font_size = terminal.font_size;
-            self.size_info.dpr = dpr;
-            self.size_info.padding_x = (f64::from(config.padding().x) * dpr).floor() as f32;
-            self.size_info.padding_y = (f64::from(config.padding().y) * dpr).floor() as f32;
-            self.update_glyph_cache(config);
-
             if new_size == None {
                 // Force a resize to refresh things
                 new_size = Some(PhysicalSize::new(
-                    f64::from(self.size_info.width),
-                    f64::from(self.size_info.height),
+                    f64::from(self.size_info.width) / self.size_info.dpr * dpr,
+                    f64::from(self.size_info.height) / self.size_info.dpr * dpr,
                 ));
             }
+
+            self.font_size = terminal.font_size;
+            self.size_info.dpr = dpr;
+            self.size_info.padding_x = (f64::from(config.padding().x) * dpr).floor() as f32;
+            self.size_info.padding_y = (f64::from(config.padding().y) * dpr).floor() as f32;
+            self.update_glyph_cache(config);
         }
         // Receive any resize events; only call gl::Viewport on last
```

</details><br>

This patch should change the current behavior to resize the terminal whenever the DPR does not match the previous DPR. I'll test this on sway once I've got it setup inside X, however it might take until tomorrow so if someone else wants to give it a shot, please let me know how it works out.

**Comment by chrisduerr** [comment]
Apparently my patch does not resolve the issue (thanks to @trimental for testing).

I'll look into why sway doesn't want to work on my machine and try playing with things myself.

**Comment by trimental** [comment]
@chrisduerr after testing on weston your patch seems to work! It looks like I was experiencing a bug in sway (wlroots).

**Comment by trimental** [comment]
@chrisduerr I tested on weston and your patch does work! It seems I was experiencing a bug in sway (wlroots)

**Comment by sodiumjoe** [comment]
@chrisduerr I've been using this branch for a while on macOS on a multimonitor (high and low DPR) and I haven't had any issues.

**Comment by jacoscaz** [comment]
Same here - multimonitor, high + low DPR, no issues.

**Comment by ndreas** [comment]
I run this on Wayland with Gnome 3.30 using one regular DPI screen and one HiDPI screen, and mostly it works really well. It's a laptop setup where the built-in screen is HiDPI and I connect to an external regular DPI screen for most of my work.

The following seems to work fine:

- Both screens enabled:
    - Dragging the window from built-in (HiDPI) to external (regular)
    - Dragging the window from external (regular) to built-in (HiDPI)
- Only external screen enabled (regular):
    - Switching to Built-in Only

In these cases the window is properly resized, the font is scaled and everything looks crisp. Sometimes, however, I can't resize the window after the move to the built-in screen.

When I have the built-in screen enabled (HiDPI) and switch to External Only there is some weirdness going on. The font turns a bit blurry, and after some input it jumps to a really tiny font.

Let me know if I can be of more assistance.

Lastly, I'd like to send a huge thanks for the work on this PR!

**Comment by SirCmpwn** [comment]
>I tested on weston and your patch does work! It seems I was experiencing a bug in sway (wlroots)

For the record, wlroots is often more strict on the Wayland protocol than Weston, and sometimes clients which work in Weston but not in Sway is not a Sway bug, but two bugs, one each in the client and in Weston.

**Comment by trimental** [comment]
@SirCmpwn After retesting I realized I couldn't reproduce the error that I was talking about before, I probably tested it wrong. 

A new issue is that if I change the output scale and then reload my config while an alacritty window is open then the contents of that window won't resize to the proper size however any new windows will be the correct size, it seems alacritty doesn't properly handle the events sway sends it to adjust to the scale.

**Comment by jwilm** [comment]
@trimental are these issues with Wayland regressions, or are they a problem on master as well?

**Comment by trimental** [comment]
@jwilm I can't produce this error on master so it seems specific to this PR

**Comment by chrisduerr** [comment]
I've looked into resolving the remaining bug and it seems there is an issue with event ordering in winit which seemingly makes it impossible to get both i3 and sway working at the moment.

I've created an issue upstream for tracking this: https://github.com/tomaka/winit/issues/663

If this can be resolved, that will hopefully allow us to get this PR fixed up and merged quickly.

**Comment by unphased** [comment]
FWIW i merged master into this branch and it is working fine.

**Comment by E5ten** [comment]
I have also been using this branch merged into master with no issues.

**Comment by chrisduerr** [comment]
I've linked this PR against a current PR of @vberger which should resolve the remaining incompatibility issues with X11/Wayland. I've tested this myself on Sway and i3 and was able to make it work on both without any regressions.

If someone still has regressions with this PR now, please let me know. As far as I'm concerned this should be good now.

Note that since this creates a local version of glutin it will still need to wait until vberger's work is upstreamed. However that should be fine for testing.

Especially a macOS test would be nice. It shouldn't be affected by this last change, however it would be nice to make sure that's the case.

**Comment by jedahan** [comment]
@chrisduerr I am trying to compile for testing on macOS, and get an error `Unable to update https://github.com/vberger/winit#fc9b7626` with the full revspec not found with `cargo build`

**Comment by vberger** [comment]
Ah yes, I have resynchronized my PR so the commit number is not longer the same.

@chrisduerr wouldn't it be easier to use my fork of winit by specifying this in the `Cargo.toml` of alacritty, rather than vendoring a glutin clone ?

```
[path.crates-io]
"winit" = { git = "https://github.com/vberger/winit.git" }
```

**Comment by chrisduerr** [comment]
Updated it to make use of the `patch` section of cargo. Should build properly again.

**Comment by sodiumjoe** [comment]
running this branch with master merged in on macOS, so far so good! I'll try with an external monitor tomorrow.

**Comment by sodiumjoe** [comment]
Works great with an external, non-hidpi monitor, too!

**Comment by chrisduerr** [comment]
Thanks for the testing @sodiumjoe! Sounds like every system should now at least kinda work. Waiting for the fix to hit upstream then.

**Comment by adrienthebo** [comment]
I've used this pull request for about a week on a 2016 15" Retina MBP and a high DPI Dell U2515H display. I haven't had a single issue so far, and the sizing has been flawless.

When I first built this branch I merged in master, and had to resolve one conflict, caused by two definitions of the section `[patch.crates-io]`, resolved with the following:

```
[patch.crates-io]
servo-freetype-sys = { path = "servo-freetype-proxy" }
"winit" = { git = "https://github.com/vberger/winit.git" }
```

The most recent merge from master into this branch introduced more conflicts, I'm going to resolve them and then keep testing this code.

**Comment by knoebber** [comment]
I'm using this on a 2018 15" MBP with external monitors . It compiled with no problems. I can confirm that Alacritty no longer shows up in the "using significant energy" list, and that it fixes the issue of dragging the Alacritty window to screens with different DPI. Before it would get tiny or huge,  now it just works. 

Thanks for your work!

**Comment by bpierce1** [comment]
2015 15" MBP: I'm using this branch, but seeing huge slowdowns. Usually if I quit Alacritty and start it from scratch, it's fine. But when I sleep my machine for awhile, then come back, Alacritty is extremely laggy. Is anyone else seeing this?

**Comment by chrisduerr** [comment]
@bpierce1 It might be that Alacritty is not using your dedicated GPU anymore, so to get a fair performance comparison you'd have to run it with your dedicated GPU and this branch.

**Comment by unphased** [comment]
@bpierce1 I have experienced the same, also on the same 2015 MBP with dGPU.

I do consider it a bug for alacritty to perform poorly on integrated. 

It's a difference of nearly 10W of power and over an hour of battery life

**Comment by chrisduerr** [comment]
@unphased Alacritty has not been using the integrated GPU before this. So for an accurate comparison you'd have to compare dedicated to dedicated, not dedicated to integrated.

**Comment by unphased** [comment]
@chrisduerr I always force the iGPU on at all times on my two MacBooks. And I monitor the battery current also.

I'd be more than happy to provide more information regarding this regression, and sorry I only have vague anecdotes so far. However I believe this is what I experience: 

a while ago, before testing this branch

2015 rMBP iGPU - great performance
2017 TB MBP iGPU - great performance

in this branch

2015 rMBP iGPU - poor performance, unclear, it usually goes away even on iGPU if MagSafe2 power is connected
2017 TB MBP iGPU - great performance

**Comment by chrisduerr** [comment]
How does this branch with dedicated GPU (you can probably force-enable it, right?) compare to the master 2015 rMBP iGPU? If it is indeed using the iGPU on master, it should not show the same behavior when using the dedicated GPU with this branch. If the performance is the same after comparing these two, chances are it's not actually using the iGPU.

I'm not familiar with macOS or how disabled the dedicated GPU really is when you force disable it. However I do know that when the dedicated GPU is available, the current master will make use of it. Since the workload isn't massive, this might not directly show in heat output.

I don't see how this PR would affect performance otherwise, iGPU/dGPU seems like the most probable cause.

**Comment by adrienthebo** [comment]
I've submitted https://github.com/mkeeler/alacritty/pull/1 with the merge-up fixes, but I think that vim was running rustfmt on all saves so the resulting conflict resolutions might be a bit large. I'll re-run the merge tonight or tomorrow.

In terms of CPU utilization, I haven't noticed anything but I've mainly been running on mains power, I'll keep an eye on load to provide another data point.

**Comment by mkeeler** [comment]
@chrisduerr I don't have a lot of time to look into things myself right now but if that PR looks good to you let me know and I will merge it promptly.

**Comment by chrisduerr** [comment]
@mkeeler I'll do that, thanks for staying in touch.

**Comment by chrisduerr** [comment]
Both #1596 and #1667 will be resolved with the next winit update. They can probably be fixed with this PR by simply running `cargo update` again once the version of winit has been bumped.

**Comment by overlazy** [comment]
@chrisduerr , And this one [#1525](https://github.com/jwilm/alacritty/issues/1525) too.

**Comment by chrisduerr** [comment]
@overlazy Thanks for the update, I wasn't aware that this issue has already been resolved upstream.

**Comment by sodiumjoe** [comment]
Just made a version bump PR into winit: https://github.com/tomaka/winit/pull/679

Once that's in, and this branch updates to use it, it will also fix #1596.

**Comment by chrisduerr** [comment]
@zacps Would you mind resolving the remaining issues for this PR on windows and testing it? It should be pretty simple but having to wait for appveyor to test changes is a bit inefficient for me.

Otherwise I'll just setup a Windows VM.

Also note that the deprecation warnings should probably be fixed, I think that's a Windows only thing.

**Comment by zacps** [comment]
Deprecation warnings will be fixed by https://github.com/jwilm/alacritty/issues/1660.

I'll try take a look at it, but it's getting pretty close to exam season for me so no promises.

**Comment by zacps** [comment]
I'm getting a significant amount of background flickering (so parts of the window are see-through) when resizing the window quickly (even with `opacity: 1.0`).

Has anyone else experienced this?

**Comment by chrisduerr** [comment]
@zacps Do these issues happen only when fixing up this PR?

You could try changing `with_transparency` in the `window.rs` to `false`. It has been an issue on other platforms before. That shouldn't be related to this PR though, but I'd still recommend giving it a shot.

**Comment by zacps** [comment]
It works fine on master, and on this branch with `with_transparency(false)`. Maybe some internal glutin changes exacerbate the problem?

I've pushed the changes needed to make it work regardless.

**Comment by chrisduerr** [comment]
I think the issues has been resolved with a previous winit/glutin update and this probably just introduces the same issue again as a regression.

Might be worth investigating this upstream, alternatively https://github.com/jwilm/alacritty/pull/1279 is still a workaround which would probably solve the issue for most people.

**Comment by zacps** [comment]
Yeah I'm happy for this to go ahead assuming we get #1279 done in the near future.

LGTM!

**Comment by chrisduerr** [comment]
Thanks @zacps. Waiting only for the upstream version bump now.

**Comment by chrisduerr** [comment]
Once [this](https://github.com/tomaka/winit/pull/680) PR is merged we'll just have to wait for a glutin version bump and then this PR can be merged too.

**Comment by vberger** [comment]
For the record, in just released `smithay-client-toolkit-0.4.1` (which can be pulled with a simple `cargo update`), fixing the two following bugs on wayland:

- keyboard compose did not work properly (for example typing `^` followed by `e` on a french keyboard did not produce `ê`), it now does
- SCTK did not properly request server-side decorations when available, it now does

**Comment by sodiumjoe** [comment]
tomaka/winit#679 has merged

**Comment by h-michael** [comment]
> Once this PR is merged we'll just have to wait for a glutin version bump and then this PR can be merged too.

Just merged !

**Comment by jwilm** [comment]
Do we need another Glutin release in order to merge this?

**Comment by chrisduerr** [comment]
@jwilm Yes, see https://github.com/tomaka/glutin/pull/1081. Thanks to @francesca64 it's already in the works and this can hopefully be merged soon.

**Comment by sodiumjoe** [comment]
https://github.com/tomaka/glutin/pull/1081 has merged 🎉
