### PR TITLE
Fix rotation of selection below 0

### LINKED ISSUE #1640: Excessive memory usage/leak during selection with less
> Which operating system does the issue occur on?
Linux X11

On Alacritty 0.2, when working with large text files (in the order of millions of lines) I am using ```less``` as I don't want the terminal itself to deal with such large numbers of lines. Nonetheless, ```scrolling.history``` is set to 100000 lines.

When I select lots of text in less using the mouse cursor, and exceed the upper or lower screen edge with the selection, Alacritty freezes and starts continuously consuming more and more memory. I managed to SIGSTOP it at 25.5GB, and it would've killed my system had I not managed to do that.

It seems something related to selections triggers a severe memory leak or unbound loop. I will try to provide better repro steps when I have the time.

### LINKED ISSUE #1643: Inverted Selection when Faux Scrolling
Rather than attempt to describe the problem in detail, here are the steps to reproduce.

1. Run `man man`
2. Scroll down  at least one line
3. Select the some text from both the status line and the line above it
4. Scroll up

You should see the selection become inverted.

### PR DESCRIPTION
**Pull request by chrisduerr**
Whenever the viewport is scrolled, the selection is rotated to make sure
that it moves with the viewport. However this did not correctly handle
the underflow that happens when the selection goes below 0.

This resolves that problem for the selection by moving the internal line
representation to an isize, thus correctly keeping track of the
selection start/end points even when they have a negative index. Once
the selection is converted to a span, the lines are clamped to the
visible region.

This fixes #1640 and fixes #1643.

Note that this currently breaks semantic and line selection because
the necessary adjustments to handle `isize`s haven't been made in their
span methods yet. This should be fairly simple, however opening a
temporary PR here should prevent unnecessary duplicated effort.

### CODE REVIEW

**Comment by chrisduerr** [comment]
I was looking into this again today and it turns out that the semantic selection is currently very broken in Alacritty in the alternate screen buffer. This includes the problem that when scrolling the selection off the screen (to the top), that the top line is only partially selected. Another issue is that copying to the clipboard does not go all the way.

Since the causes for this are a little more complicated, this will probably need a bit more work. Currently the semantic selection is updated quite frequently whenever the selection is converted to a span. I would assume that this requires to be changed.

File: src/index.rs [hunk 1]
```diff
@@ -52,6 +52,18 @@ impl Ord for Point {
     }
 }
 
+impl From<Point<usize>> for Point<isize> {
```
Comment (zacps) [inline src/index.rs]: Is there any reason we use both `usize` and `isize` instead of just `isize`?

Comment (chrisduerr) [reply src/index.rs]: Well generally the index should never be negative. And it actually never is negative in the normal screen buffer. So we use `usize` for most stuff internally.

But with the alternate screen buffer, scrolling doesn't actually scroll a buffer, there's not actually anything going up/down, because the alternate screen buffer has only the visible region. As a result the line `0` is always the bottom, so if we want to keep track of everything below that, using negative lines seems reasonable. Thus the `isize` stuff.

It doesn't make much sense to do this for the complete codebase though, since most scenarios never want to keep track of anything outside of the terminal emulator. So for all other places the only thing relevant is the offset from the bottom of all lines, which is `0`. So a `usize` works perfectly.

I've decided to use `event.rs` as a hand-off point for this since it is an intermediate step between `input.rs` and `selection.rs`. So everything talking to it can just use the standard `usize` which are used everywhere and then the selection can take over which actually has a concept of lines below the terminal emulator.

Note that this PR still needs another clean-up pass. So some things might seem nonsensical (haven't looked at the resulting diff yet). But the general idea shouldn't be totally off.

**Comment by chrisduerr** [comment]
Cleaned things up a bit and added some tests to prevent potential regressions.

If all tests pass, this should be good to go as far as I'm concerned.
