### PR TITLE
Move to cargo clippy

### LINKED ISSUE #1341: Not properly working on Ubuntu 18.04
Which operating system does the issue occur on?
Ubuntu 18.04
If on linux, are you using X11 or Wayland?
x11  
Fresh install of Ubuntu 18.04 on the newest version of Virtual Box running off my Windows 10 machine. I installed rust through rustup and followed the install process for alacritty. When running the command `alacritty`, I get an error: 
> name@hduiw10:~$ alacritty 
[winit X11 error] XError {
    description: "BadValue (integer parameter out of range for operation)",
    error_code: 2,
    request_code: 12,
    minor_code: 0
}  

Alacritty launches but with significant scaling issues:
github_issue
(screenshot taken with gnome-screenshot -wB & help was run in alacritty 3 times. Also note that when I run help, the output was printed side by side twice each time)  
No errors were present in installing anything. Let me know if you want any logs.

### LINKED ISSUE #1344: XCB aborting
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

I get this every now and then when I launch Alacritty.

```
$ alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/niklas/.config/alacritty.yml
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
alacritty: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
```

### PR DESCRIPTION
**Pull request by chrisduerr**
Using clippy as a library has been deprecated, instead the `cargo
clippy` command should be used instead. To comply with this change
clippy has been removed from the `Cargo.toml` and is now installed with
cargo when building in CI.

This has also lead to a few new clippy issues to show up, this includes
everything in the `font` subdirectory. This has been fixed and `font`
should now be covered by clippy CI too.

This also upgrades all dependencies, as a result this fixes #1341 and
this fixes #1344.

### CODE REVIEW

File: font/src/darwin/mod.rs [hunk 1]
```diff
@@ -482,13 +481,13 @@ impl Font {
         }
 
         let glyph_index = self.glyph_index(character)
-            .ok_or(Error::MissingGlyph(character))?;
+            .ok_or_else(|| Error::MissingGlyph(character))?;
```
Comment (nixpulvis) [inline font/src/darwin/mod.rs]: :eyes:

Comment (chrisduerr) [reply font/src/darwin/mod.rs]: Do you have any issue with this change?

Comment (nixpulvis) [reply font/src/darwin/mod.rs]: No, I'm just kinda surprised.

Comment (chrisduerr) [reply font/src/darwin/mod.rs]: Ah okay, it's an interesting one:

`ok_or` is not lazy, so `Error::MissingGlpyh(character)` is always called, even if the result is `Ok`. So this should only be used for stuff like `32` where no expensive initialization is required.

However with `ok_or_else` this is done lazily, so `Error::MissingGlyph(character)` is only called if the result is `Err` and not okay, so we save ourselves the call if the result is `Ok`.

This is a pretty interesting lint imho because I think a lot of people don't know this difference. At least I was only made aware of it when I first saw the clippy lint, but it makes sense when you take a look at it knowing what it does.

**Comment by chrisduerr** [comment]
@sodiumjoe I've removed the `let _ : () = ...` stuff from the `locale.rs` file to resolve the clippy warnings, however I think there was a reason why we did this. Do you remember why this was added? I think it might have been you who put this in.

It seems like all the tests run through and there are no compiler warnings, so maybe this is not needed anymore?

**Comment by chrisduerr** [comment]
Since this also updates all dependencies, I'd like to wait for the new winit release so all the cleanup and updating of dependencies can just be done in one commit rather than updating winit twice.

Since a new version of winit should be released pretty soon, that shouldn't block this for very long.
