### PR TITLE
Maximize window after mapping

### LINKED ISSUE #1902: start_maximized doesn't work on KDE
Which operating system does the issue occur on?
ThinkPad x1 carbon 5gen(1920×1080)
Latest KDE neon

If on linux, are you using X11 or Wayland?
X11

Width not be maximized.

### PR DESCRIPTION
**Pull request by CrackedP0t**
Because Alacritty's window starts out unmapped with `with_visibility(false)`, adding `with_maximized()` makes Winit try to maximize the window before it's mapped. Compliant window managers ignore the request, so when `show()` is called, it's not maximized. This pull request explicitly maximizes the window after it's mapped, and fixes #1902.

### CODE REVIEW

**Comment by CrackedP0t** [comment]
Alright, now on all platforms it calls `with_maximized()` on the builder, so it will start maximized on all platforms except X11, and it's possible that some WMs will let it start maximized before mapping. Then, on X11 only, it will maximize it after `show()`.

File: src/window.rs [hunk 1]
```diff
@@ -139,6 +140,11 @@ impl Window {
             .or_else(|_| create_gl_window(window_builder, &event_loop, true))?;
         window.show();
 
+        // Maximize window after mapping in X11
+        if cfg!(not(any(target_os = "macos", windows))) && event_loop.is_x11() {
```
Comment (chrisduerr) [inline src/window.rs]: We should use `#[cfg(...)]` here instead of `cfg!`. It's a little uglier since it requires an extra scope, but that makes sure it's only checked at compile-time.

File: CHANGELOG.md [hunk 2]
```diff
@@ -47,6 +47,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Fixes increase/decrease font-size keybindings on international keyboards
 - On Wayland, the `--title` flag will set the Window title now
 - Parsing issues with URLs starting in the first or ending in the last column
+- Fix not starting maximized on X11
```
Comment (chrisduerr) [inline CHANGELOG.md]: I think we can improve this a little bit. Right now people might think this means Alacritty will always start maximized, which is not the case.

So we should say that this fixed not starting maximized on X11 when the config setting is enabled.

File: src/window.rs (hunk 1 above)
Comment (CrackedP0t) [reply src/window.rs]: Oh, OK, thanks - yeah, on MacOS and Windows it was failing because of that.

File: CHANGELOG.md (hunk 2 above)
Comment (CrackedP0t) [reply CHANGELOG.md]: Alright, changed that

File: src/window.rs [hunk 3]
```diff
@@ -141,8 +141,11 @@ impl Window {
         window.show();
 
         // Maximize window after mapping in X11
-        if cfg!(not(any(target_os = "macos", windows))) && event_loop.is_x11() {
-            window.set_maximized(window_config.start_maximized());
+        #[cfg(not(any(target_os = "macos", windows)))]
+        {
+            if event_loop.is_x11() {
+                window.set_maximized(window_config.start_maximized());
```
Comment (chrisduerr) [inline src/window.rs]: Another issue with doing it like this is that we could be potentially unsetting the WMs maximized state if a user sets the window to maximized through the WM instead of Alacritty.

So when using `set_maximized` after start, we should only do so when maximized is `true`, we shouldn't unmaximize the window when it is `false`.

So `if event_loop.is_x11() && window_config.start_maximized() { window.set_maximized(true); }` is probably what we want.
