### PR TITLE
Fix rendering of selections outside the viewport

### LINKED ISSUE #1557: Selecting large amounts of text makes highlight disappear
> Which operating system does the issue occur on?

Linux X11

When selecting text and scrolling at the same time using the new scrolling->history feature, there is a visual bug concering the selected text.

When more text is selected than fits on the viewport, and the viewport is scrolled so that **only** selected text is visible, the selection marker (inverted colors) disappears. If the viewport is scrolled so that only parts of its contents are selected, the selection marker shows up fine.

### PR DESCRIPTION
**Pull request by chrisduerr**
When rendering selections with both start and end outside of the visible
area, Alacritty would assume that both start and end are either above or
below the viewport and not render the selection at all.

To fix this the `buffer_line_to_visible` method now returns a
`ViewportPosition` instead of an `Option<Line>`, this allows giving more
feedback about where outside of the visible region the line is using the
`ViewportPosition::Above` and `ViewportPosition::Below` varients.

Using these newly introduced varients, a selection spanning the whole
screen is now rendered if the selection should go from above the visible
area to below it.

This fixes #1557.

### CODE REVIEW

File: src/grid/mod.rs [hunk 1]
```diff
@@ -300,11 +300,11 @@ impl<T: Copy + Clone> Grid<T> {
...
     }
 
-    pub fn offset_to_line(&self, offset: usize) -> Option<Line> {
+    fn offset_to_line(&self, offset: usize) -> ViewportPosition {
         if offset < *self.num_lines() {
-            Some(self.lines - offset - 1)
+            ViewportPosition::Visible(self.lines - offset - 1)
         } else {
-            None
+            ViewportPosition::Above
```
Comment (nixpulvis) [inline src/grid/mod.rs]: Would it make sense to remove the `offset_to_line` function altogether and put all three cases in `buffer_line_to_visible`? I find myself expecting to see three cases in one place from the definition of `ViewportPosition`.

Comment (chrisduerr) [reply src/grid/mod.rs]: Originally this function had a `pub` before it for external use, which I guess was the reason it hasn't been merged with the other function yet. But since it's not used anywhere else and I've just removed the `pub` declaration, merging these two together seems like a good idea.

Thanks for the feedback.
